SELECT * FROM SML_SECURITY WHERE ASSESSMENT_OF_COLLATERAL IS NULL ;

SELECT SEC.ID, A.CA_ID, 
    B.Title_Number_prefix, rawtohex(B.Title_Number_prefix),
    B. Lot_No, rawtohex(Lot_No),
    B.Lot_Number_prefix, rawtohex(Lot_Number_prefix),
    B.postcode, rawtohex(postcode),
    B.Phy_inspect_freq_unit, rawtohex(Phy_inspect_freq_unit),
    B.Property_Address, rawtohex(Property_Address),
    B.Assessment, rawtohex(Assessment),
    B.district, rawtohex(district),
    B.ABANDONED_PROJECT, rawtohex(ABANDONED_PROJECT),
    B.INDEPENDENT_VALUER_FLAG, rawtohex(INDEPENDENT_VALUER_FLAG),
    B.PROJECT_NAME, rawtohex(PROJECT_NAME),
	B.NON_PREFERRED_LOCATION, rawtohex(NON_PREFERRED_LOCATION),
    B.property_completion_stage, rawtohex(property_completion_stage),
    B.scheduled_location, rawtohex(scheduled_location),
    B.MORTGAGE_TYPE, rawtohex(MORTGAGE_TYPE),
    B.TENANT_TYPE, rawtohex(TENANT_TYPE),
    SEC.EXCHANGE_CONTROL_OBTAINED, rawtohex(EXCHANGE_CONTROL_OBTAINED),
    SEC.SCI_REFERENCE_NOTE,rawtohex(SCI_REFERENCE_NOTE),
    SEC.SCI_SECURITY_CCY, rawtohex(SCI_SECURITY_CCY),
    SEC.SOURCE_ID, rawtohex(SEC.SOURCE_ID),
    SEC.COLLATERAL_DESCRIPTION, rawtohex(SEC.COLLATERAL_DESCRIPTION),
    SEC.COLLATERAL_NAME,rawtohex(SEC.COLLATERAL_NAME),
	SEC.ASSESSMENT_OF_COLLATERAL,rawtohex(SEC.ASSESSMENT_OF_COLLATERAL)
FROM 
SML_SECURITY SEC
LEFT JOIN sml_ca_collateral A ON SEC.ID = A.COLLATERAL_ID 
LEFT JOIN SML_SEC_PT B ON SEC.ID= B.ID 
LEFT JOIN sml_pledgor C ON C.COLLATERAL_ID = SEC.ID
LEFT JOIN sml_customer D ON D.ID = C.owner_id
LEFT JOIN SML_SEC_VALUATION E ON E.Collateral_id = sec.id 
WHERE A.CA_ID IN ( SELECT CA_ID FROM sml_ca_collateral WHERE COLLATERAL_ID  = 202207210022499345);

SELECT SEC.ID, ASSESSMENT_OF_COLLATERAL,rawtohex(ASSESSMENT_OF_COLLATERAL) FROM SML_SECURITY SEC 
WHERE SEC.ID IN(202207210022499345,202207210022499346,202207210022499407) AND rawtohex(ASSESSMENT_OF_COLLATERAL) like '%' || chr(0) || '%' ;
SELECT SEC.ID,  ASSESSMENT_OF_COLLATERAL,dump(ASSESSMENT_OF_COLLATERAL) str FROM SML_SECURITY SEC 
WHERE SEC.ID IN(202207210022499345,202207210022499346,202207210022499407) AND  dump(ASSESSMENT_OF_COLLATERAL) like '%' || chr(0) || '%' ;
SELECT SEC.ID,  COLLATERAL_DESCRIPTION,rawtohex(COLLATERAL_DESCRIPTION) FROM SML_SECURITY SEC 
WHERE SEC.ID IN(202207210022499345,202207210022499346,202207210022499407) AND rawtohex(COLLATERAL_DESCRIPTION) like '%' || chr(0) || '%' ;
SELECT SEC.ID, COLLATERAL_DESCRIPTION,dump(COLLATERAL_DESCRIPTION) str FROM SML_SECURITY SEC 
WHERE SEC.ID IN(202207210022499345,202207210022499346,202207210022499407) AND dump(ASSESSMENT_OF_COLLATERAL) like '%' || chr(0) || '%' ;