CREATE OR REPLACE PROCEDURE GLBATCH
AS
    V_TOTALRECORD            NUMBER;

BEGIN

    EXECUTE IMMEDIATE 'TRUNCATE TABLE LOS_BATCH_GL_DETAIL';
    BEGIN

        INSERT INTO LOS_BATCH_GL_DETAIL(REC_INDICATOR, SOURCE_SYSTEM_CODE, EFFECTIVE_DATE, TRANSACTION_DATE , PRODUCT_CODE, ENTERED_AMOUNT , ACCOUNTED_AMOUNT , TRANSACTION_NO, ADDITIONAL_1)
        SELECT
          'D' AS REC_INDICATOR,
	      'RSL' AS SOURCE_SYSTEM_CODE ,
	      TO_CHAR(SYSDATE,'DDMMYY') , TO_CHAR(SYSDATE,'DDMMYY') ,
          (SELECT SERVICE_PROGRAM FROM LOS_FAC_PRC PRC WHERE PRC.FAC_ID = FAC.ID AND PRC.PRC_TYPE IS NULL AND ROWNUM = 1) AS PRODUCT_CODE,
          RR.TOTAL_REVOLVING_CASHBACK_AMT AS ENTERED_AMOUNT ,
          RR.TOTAL_REVOLVING_CASHBACK_AMT AS  ACCOUNTED_AMOUNT ,
	      fac.CA_ID AS TRANSACTION_NO,
          fac.HOST_ACCT_NO AS  ADDITIONAL_1
		FROM LOS_CA CA
	    LEFT JOIN LOS_FAC FAC ON CA.ID = FAC.CA_ID
            LEFT JOIN LOS_WF_TASK_ARCHIVED WFA ON WFA.APP_ID = CA.ID
            LEFT JOIN LOS_REG_REQUEST RR ON RR.CA_ID = CA.ID
            WHERE CA.APP_TYP = 'MO'
            AND CA.INTEGRATION_STS_6 = 'DIRECTCREDIT_SUCCESS'
            AND RR.TOTAL_REVOLVING_CASHBACK_AMT > 0
            AND WFA.APP_STATUS = 'STPCP'
		ORDER BY CA.ID;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
           NULL;
    END;

    --get total records
    SELECT COUNT(1) INTO V_TOTALRECORD FROM LOS_BATCH_GL_DETAIL;
    DBMS_OUTPUT.PUT_LINE( 'v_totalRecord=>'||V_TOTALRECORD);

    COMMIT;

END GLBATCH;
/

INSERT INTO LOS_SYS_DB_VERSION VALUES ('CYH CR','20230301','DB Patch','on-site team','GLBATCH', SYSDATE);
COMMIT;
