SET TERMOUT OFF
SET NEWPAGE NONE
SET SPACE 0
SET LINESIZE 3312
SET PAGESIZE 88
SET ECHO OFF
SET FEEDBACK OFF
SET HEADING OFF
SET WRAP OFF
SET TRIMSPOOL OFF
SET SERVEROUTPUT ON SIZE 1000000
WHENEVER OSERROR EXIT SQLERRM
WHENEVER SQLERROR EXIT SQLERRM

COLUMN no_row new_val var_no_row noprint
COLUMN outpath new_val var_outpath noprint
COLUMN date_path new_val date_path noprint

-- Start export data
SELECT '/oracledata/RLOSBATCH/GL_Batch/output/RSL_FAH_E_'||TO_CHAR(SYSDATE,'YYYYMMDD')||'_001.txt' date_path FROM DUAL;

SPOOL &date_path;

SELECT
	REC_INDICATOR ||'|'||
	LEDGER ||'|'||
	SOURCE_SYSTEM_CODE ||'|'||
	EFFECTIVE_DATE ||'|'||
	TRANSACTION_DATE ||'|'||
	EVENT_DESC ||'|'||
	ENTITY_CODE ||'|'||
	INTERCOMPANY_CODE ||'|'||
	OWNER_BRANCH_CODE ||'|'||
	ENTRY_BRANCH_CODE ||'|'||
	DESTINATION_BRANCH_CODE ||'|'||
	OWNER_OFFICE_CODE ||'|'||
	ENTRY_OFFICE_CODE ||'|'||
	DESTINATION_OFFICE_CODE ||'|'||
	CUSTOMER_CODE ||'|'||
	PRODUCT_CODE ||'|'||
	CHANNEL_CODE ||'|'||
	PROJECT_CODE ||'|'||
	TAX_CODE ||'|'||
	ENTERED_AMOUNT ||'|'||
	ENTERED_CURRENCY_CODE ||'|'||
	EXCHANGE_RATE_TYPE ||'|'||
	EXCHANGE_RATE ||'|'||
	EXCHANGE_RATE_DATE ||'|'||
	ACCOUNTED_AMOUNT ||'|'||
	ACCOUNTED_CURRENCY_CODE ||'|'||
	JOURNAL_LINE_DESCRIPTION ||'|'||
	TRANSACTION_NO ||'|'||
	GL_REFERENCE_NUMBER ||'|'||
	CUSTOMER_TYPE ||'|'||
	TAX_NO ||'|'||
	TAX_DATE ||'|'||
	PAYMENT_DATE ||'|'||
	TAX_ID ||'|'||
	TAX_NAME ||'|'||
	TAX_ADDRESS_1 ||'|'||
	TAX_ADDRESS_2 ||'|'||
	TAX_ADDRESS_3 ||'|'||
	RD_PLACE ||'|'||
	RD_TAX_BRANCH ||'|'||
	WHT_TAX_RATE ||'|'||
	WHT_TAX_TYPE ||'|'||
	TAX_BASE ||'|'||
	TAX_AMOUNT ||'|'||
	INCOME_TYPE ||'|'||
	CUSTOMER_ACCOUNT_NO ||'|'||
	DEPOSIT_TD_NUMBER ||'|'||
	CHEQUE_NUMBER_FROM ||'|'||
	CHEQUE_NUMBER_TO ||'|'||
	TOTAL_COUNT_FOR_CHEQUE ||'|'||
	CHEQUE_AMOUNT ||'|'||
	CONTRACT_DATE ||'|'||
	DUE_DATE ||'|'||
	NOSTRO_BANK_ACCOUNT_NUMBER ||'|'||
	NOSTRO_BANK_REFERENCE_NUMBER ||'|'||
	NOSTRO_VALUE_DATE ||'|'||
	NOSTRO_DUE_DATE ||'|'||
	ADDITIONAL_1 ||'|'||
	ADDITIONAL_2 ||'|'||
	ADDITIONAL_3 ||'|'||
	ADDITIONAL_4 ||'|'||
	ADDITIONAL_5 ||'|'||
	ADDITIONAL_6 ||'|'||
	ADDITIONAL_7 ||'|'||
	ADDITIONAL_8 ||'|'||
	ADDITIONAL_9 ||'|'||
	ADDITIONAL_10 ||'|'||
	ADDITIONAL_11 ||'|'||
	ADDITIONAL_12 ||'|'||
	ADDITIONAL_13 ||'|'||
	ADDITIONAL_14 ||'|'||
	ADDITIONAL_15 ||'|'||
	ADDITIONAL_ENTERED_AMT_1 ||'|'||
	ADDITIONAL_ENTERED_AMT_CURR_CODE_1 ||'|'||
	ADDITIONAL_ENTERED_EXCHANGE_RATE_TYPE_1 ||'|'||
	ADDITIONAL_ENTERED_EXCHANGE_RATE_1 ||'|'||
	ADDITIONAL_ACCOUNTED_AMT_1 ||'|'||
	ADDITIONAL_ACCOUNTED_AMT_CURR_CODE_1 ||'|'||
	ADDITIONAL_ENTERED_AMT_2 ||'|'||
	ADDITIONAL_ENTERED_AMT_CURR_CODE_2 ||'|'||
	ADDITIONAL_ENTERED_EXCHANGE_RATE_TYPE_2 ||'|'||
	ADDITIONAL_ENTERED_EXCHANGE_RATE_2 ||'|'||
	ADDITIONAL_ACCOUNTED_AMT_2 ||'|'||
	ADDITIONAL_ACCOUNTED_AMT_CURR_CODE_2 ||'|'||
	ADDITIONAL_ENTERED_AMT_3 ||'|'||
	ADDITIONAL_ENTERED_AMT_CURR_CODE_3 ||'|'||
	ADDITIONAL_ENTERED_EXCHANGE_RATE_TYPE_3 ||'|'||
	ADDITIONAL_ENTERED_EXCHANGE_RATE_3 ||'|'||
	ADDITIONAL_ACCOUNTED_AMT_3 ||'|'||
	ADDITIONAL_ACCOUNTED_AMT_CURR_CODE_3 ||'|'||
	ADDITIONAL_ENTERED_AMT_4 ||'|'||
	ADDITIONAL_ENTERED_AMT_CURR_CODE_4 ||'|'||
	ADDITIONAL_ENTERED_EXCHANGE_RATE_TYPE_4 ||'|'||
	ADDITIONAL_ENTERED_EXCHANGE_RATE_4 ||'|'||
	ADDITIONAL_ACCOUNTED_AMT_4 ||'|'||
	ADDITIONAL_ACCOUNTED_AMT_CURR_CODE_4 ||'|'||
	ADDITIONAL_ENTERED_AMT_5 ||'|'||
	ADDITIONAL_ENTERED_AMT_CURR_CODE_5 ||'|'||
	ADDITIONAL_ENTERED_EXCHANGE_RATE_TYPE_5 ||'|'||
	ADDITIONAL_ENTERED_EXCHANGE_RATE_5 ||'|'||
	ADDITIONAL_ACCOUNTED_AMT_5 ||'|'||
	ADDITIONAL_ACCOUNTED_AMT_CURR_CODE_5 ||'|'||
	ADDITIONAL_ENTERED_AMT_6 ||'|'||
	ADDITIONAL_ENTERED_AMT_CURR_CODE_6 ||'|'||
	ADDITIONAL_ENTERED_EXCHANGE_RATE_TYPE_6 ||'|'||
	ADDITIONAL_ENTERED_EXCHANGE_RATE_6 ||'|'||
	ADDITIONAL_ACCOUNTED_AMT_6 ||'|'||
	ADDITIONAL_ACCOUNTED_AMT_CURR_CODE_6 ||'|'||
	ADDITIONAL_ENTERED_AMT_7 ||'|'||
	ADDITIONAL_ENTERED_AMT_CURR_CODE_7 ||'|'||
	ADDITIONAL_ENTERED_EXCHANGE_RATE_TYPE_7 ||'|'||
	ADDITIONAL_ENTERED_EXCHANGE_RATE_7 ||'|'||
	ADDITIONAL_ACCOUNTED_AMT_7 ||'|'||
	ADDITIONAL_ACCOUNTED_AMT_CURR_CODE_7 ||'|'||
	ADDITIONAL_ENTERED_AMT_8 ||'|'||
	ADDITIONAL_ENTERED_AMT_CURR_CODE_8 ||'|'||
	ADDITIONAL_ENTERED_EXCHANGE_RATE_TYPE_8 ||'|'||
	ADDITIONAL_ENTERED_EXCHANGE_RATE_8 ||'|'||
	ADDITIONAL_ACCOUNTED_AMT_8 ||'|'||
	ADDITIONAL_ACCOUNTED_AMT_CURR_CODE_8 ||'|'||
	ADDITIONAL_ENTERED_AMT_9 ||'|'||
	ADDITIONAL_ENTERED_AMT_CURR_CODE_9 ||'|'||
	ADDITIONAL_ENTERED_EXCHANGE_RATE_TYPE_9 ||'|'||
	ADDITIONAL_ENTERED_EXCHANGE_RATE_9 ||'|'||
	ADDITIONAL_ACCOUNTED_AMT_9 ||'|'||
	ADDITIONAL_ACCOUNTED_AMT_CURR_CODE_9 ||'|'||
	ADDITIONAL_ENTERED_AMT_10 ||'|'||
	ADDITIONAL_ENTERED_AMT_CURR_CODE_10 ||'|'||
	ADDITIONAL_ENTERED_EXCHANGE_RATE_TYPE_10 ||'|'||
	ADDITIONAL_ENTERED_EXCHANGE_RATE_10 ||'|'||
	ADDITIONAL_ACCOUNTED_AMT_10 ||'|'||
	ADDITIONAL_ACCOUNTED_AMT_CURR_CODE_10 ||'|'
FROM LOS_BATCH_GL_DETAIL;

--FOOTER
SELECT 'T' || '|' ||
    RES.TOTAL || '|' ||
     NVL( RES.SUM_AMT , 0 )     || '|' || ''
     FROM (SELECT COUNT(*) AS TOTAL, SUM(ENTERED_AMOUNT) AS SUM_AMT FROM LOS_BATCH_GL_DETAIL) RES ;

SPOOL OFF;

CLEAR COLUMN COMPUTE BREAK

exit


