	-- // Get Checklist of Col
	-- public HashMap getCollateralCheckListStatus(long aLimitProfileID) throws SearchDAOException {

SELECT CMS_CHECKLIST.CHECKLIST_ID, CMS_CHECKLIST.CMS_LSP_LMT_PROFILE_ID, CMS_CHECKLIST.MASTERLIST_ID,
CMS_CHECKLIST.CMS_COLLATERAL_ID, CMS_CHECKLIST.CMS_LMP_SUB_PROFILE_ID, CMS_CHECKLIST.CMS_PLEDGOR_DTL_ID, CMS_CHECKLIST.IS_MASTER_CHECKLIST,
CMS_CHECKLIST.CATEGORY, CMS_CHECKLIST.SUB_CATEGORY, CMS_CHECKLIST.STATUS, CMS_CHECKLIST.DOC_ORIG_COUNTRY, CMS_CHECKLIST.APPLICATION_TYPE, 
CMS_CHECKLIST.DOC_ORIG_ORGANISATION, CMS_CHECKLIST.ALLOW_DELETE_IND,CMS_CHECKLIST.disable_collaboration_ind, 
TRANSACTION.TRANSACTION_ID, TRANSACTION.STATUS AS TRX_STATUS,TRANSACTION.FROM_STATE 
FROM CMS_CHECKLIST, TRANSACTION 
WHERE TRANSACTION.REFERENCE_ID = CMS_CHECKLIST.CHECKLIST_ID 
AND TRANSACTION.TRANSACTION_TYPE = 'CHECKLIST' AND TRANSACTION.STATUS <> 'OBSOLETE'
AND 
    CMS_CHECKLIST.CMS_LSP_LMT_PROFILE_ID =  ?
AND CMS_CHECKLIST.CATEGORY = 'S' ;

IS_MASTER_CHECKLIST


