
 SELECT * FROM HK_TRANSACTION ;
SELECT * FROM HK_CMS_FACILITY_MASTER;
SELECT * FROM HK_CMS_FAC_RELATIONSHIP;
SELECT * FROM HK_CMS_FAC_MULTI_TIER_FINANCING;
SELECT * FROM HK_CMS_FACILITY_MASTER;

SELECT * FROM  HK_CMS_ASSET_PLANT_EQUIP;
SELECT * FROM  HK_CMS_ASSET_TRADE_IN;
SELECT * FROM  HK_CMS_ASSET_VEHICLE;
SELECT * FROM  HK_CMS_ASSET_VESSEL;
SELECT * FROM  HK_cms_checklist;
SELECT * FROM  HK_cms_checklist_item;
SELECT * FROM  HK_cms_cust_doc;
SELECT * FROM  HK_cms_cust_doc_item;

SELECT * FROM CMS_CUST_DOC_ITEM WHERE CHECKLIST_ITEM_REF_ID = 20130618000000004 ;