DROP TABLE HK_cms_cash_deposit ;
DROP TABLE HK_sci_sec_pldgr_map;
DROP TABLE HK_cms_ca_collateral_map;
DROP TABLE HK_CMS_CHARGE_DETAIL;
DROP TABLE HK_CMS_LIMIT_CHARGE_MAP ;
DROP TABLE HK_cms_limit_security_map;
DROP TABLE HK_CMS_ASSET;
DROP TABLE HK_CMS_CASH;
DROP TABLE HK_CMS_ASSET_PDC;
DROP TABLE HK_CMS_VALUATION;
DROP TABLE HK_CMS_INSURANCE;
DROP TABLE HK_CMS_INSURANCE_CDS;
DROP TABLE HK_CMS_MARKETABLE_SEC;
DROP TABLE HK_CMS_PORTFOLIO_ITEM;
DROP TABLE HK_CMS_DOCUMENT;
DROP TABLE HK_CMS_OTHERS;
DROP TABLE HK_CMS_GUARANTEE;
DROP TABLE HK_CMS_PROPERTY;
DROP TABLE HK_CMS_INSURANCE_POLICY;
DROP TABLE HK_CMS_ASSET_AIRCRAFT;
DROP TABLE HK_CMS_ASSET_GOLD;

DROP TABLE HK_CMS_ASSET_PLANT_EQUIP;
DROP TABLE HK_CMS_ASSET_TRADE_IN;
DROP TABLE HK_CMS_ASSET_VEHICLE;
DROP TABLE HK_CMS_ASSET_VESSEL;
DROP TABLE HK_cms_checklist;
DROP TABLE HK_cms_checklist_item;
DROP TABLE HK_cms_cust_doc;
DROP TABLE HK_cms_cust_doc_item;
DROP TABLE HK_TRANSACTION;
DROP TABLE HK_TRANS_HISTORY;
DROP TABLE HK_CMS_STG_FACILITY_MASTER;
DROP TABLE HK_CMS_STG_FAC_RELATIONSHIP ;
DROP TABLE HK_CMS_STG_FAC_MULTI_TIER_FINANCI;
DROP TABLE HK_CMS_STG_FAC_PREPAYMENT_LIST;
DROP TABLE HK_CMS_STG_FAC_REDUCTION_SCHEDULE;
DROP TABLE HK_CMS_STG_LSP_APPR_DRAWING_CURR;
DROP TABLE HK_CMS_STG_FAC_MESSAGE;
DROP TABLE HK_CMS_STG_FAC_INCREMENTAL;

DROP TABLE HK_CMS_STG_FAC_GENERAL ;
DROP TABLE HK_CMS_STG_FAC_INTEREST;
DROP TABLE HK_CMS_STG_FAC_ADDITIONAL;
DROP TABLE HK_CMS_STG_FAC_FEE_CHARGE;
DROP TABLE HK_CMS_STG_FAC_BNM_CODES;
DROP TABLE HK_CMS_STG_FAC_ISLAMIC_MASTER;
DROP TABLE HK_CMS_STG_FAC_BBA_VARI_PACKAGE;
DROP TABLE HK_CMS_STG_FAC_RENTAL_RENEWAL;
DROP TABLE HK_CMS_STG_FAC_SECURITY_DEPOSIT;
DROP TABLE HK_CMS_STG_FAC_TSPR;
DROP TABLE HK_CMS_STAGE_SECURITY;
DROP TABLE HK_CMS_STAGE_cash_deposit ;
DROP TABLE HK_CMS_STAGE_CHARGE_DETAIL;
DROP TABLE HK_CMS_STAGE_LIMIT_CHARGE_MAP ;
DROP TABLE HK_CMS_STAGE_limit_security_map;
DROP TABLE HK_CMS_STAGE_ASSET;
DROP TABLE HK_CMS_STAGE_CASH;
DROP TABLE HK_CMS_STAGE_ASSET_PDC;
DROP TABLE HK_CMS_STAGE_VALUATION;
DROP TABLE HK_CMS_STAGE_INSURANCE;
DROP TABLE HK_CMS_STAGE_INSURANCE_CDS;
DROP TABLE HK_CMS_STAGE_MARKETABLE_SEC;
DROP TABLE HK_CMS_STAGE_PORTFOLIO_ITEM;
DROP TABLE HK_CMS_STAGE_DOCUMENT;
DROP TABLE HK_CMS_STAGE_OTHERS;
DROP TABLE HK_CMS_STAGE_GUARANTEE;
DROP TABLE HK_CMS_STAGE_PROPERTY;
DROP TABLE HK_CMS_STAGE_INSURANCE_POLICY;
DROP TABLE HK_CMS_STAGE_ASSET_AIRCRAFT;
DROP TABLE HK_CMS_STAGE_ASSET_GOLD;

DROP TABLE HK_CMS_STAGE_ASSET_PLANT_EQUIP;
DROP TABLE HK_STAGE_ASSET_TRADE_IN;
DROP TABLE HK_CMS_STAGE_ASSET_VEHICLE;
DROP TABLE HK_CMS_STAGE_ASSET_VESSEL;
DROP TABLE HK_STAGE_CHECKLIST;
DROP TABLE HK_STAGE_CHECKLIST_ITEM;
DROP TABLE HK_cms_stage_cust_doc;
DROP TABLE HK_cms_stage_cust_doc_item;

DROP TABLE HK_sci_lsp_appr_lmts;

-- MAIN TABLE
CMS_SECURITY
cms_cash_deposit 
sci_sec_pldgr_map
cms_ca_collateral_map
CMS_CHARGE_DETAIL
CMS_LIMIT_CHARGE_MAP 
cms_limit_security_map
CMS_ASSET
CMS_CASH
CMS_ASSET_PDC
CMS_VALUATION
CMS_INSURANCE
CMS_INSURANCE_CDS
CMS_MARKETABLE_SEC
CMS_PORTFOLIO_ITEM
CMS_DOCUMENT
CMS_OTHERS
CMS_GUARANTEE
CMS_PROPERTY
CMS_INSURANCE_POLICY
CMS_ASSET_AIRCRAFT
CMS_ASSET_GOLD
CMS_ASSET_PDC
CMS_ASSET_PLANT_EQUIP
CMS_ASSET_TRADE_IN
CMS_ASSET_VEHICLE
CMS_ASSET_VESSEL
cms_checklist
cms_checklist_item
cms_cust_doc
cms_cust_doc_item
TRANSACTION
TRANS_HISTORY
CMS_STG_FACILITY_MASTER
CMS_STG_FAC_RELATIONSHIP 
CMS_STG_FAC_MULTI_TIER_FINANCI
CMS_STG_FAC_PREPAYMENT_LIST
CMS_STG_FAC_REDUCTION_SCHEDULE
CMS_STG_LSP_APPR_DRAWING_CURR
CMS_STG_FAC_MESSAGE
CMS_STG_FAC_INCREMENTAL
CMS_STG_FAC_REDUCTION_SCHEDULE
CMS_STG_FAC_GENERAL 
CMS_STG_FAC_INTEREST
CMS_STG_FAC_ADDITIONAL
CMS_STG_FAC_FEE_CHARGE
CMS_STG_FAC_BNM_CODES
CMS_STG_FAC_ISLAMIC_MASTER
CMS_STG_FAC_BBA_VARI_PACKAGE
CMS_STG_FAC_RENTAL_RENEWAL
CMS_STG_FAC_SECURITY_DEPOSIT
CMS_STG_FAC_TSPR
CMS_STAGE_SECURITY
CMS_STAGE_cash_deposit 
CMS_STAGE_CHARGE_DETAIL
CMS_STAGE_LIMIT_CHARGE_MAP 
CMS_STAGE_limit_security_map
CMS_STAGE_ASSET
CMS_STAGE_CASH
CMS_STAGE_ASSET_PDC
CMS_STAGE_VALUATION
CMS_STAGE_INSURANCE
CMS_STAGE_INSURANCE_CDS
CMS_STAGE_MARKETABLE_SEC
CMS_STAGE_PORTFOLIO_ITEM
CMS_STAGE_DOCUMENT
CMS_STAGE_OTHERS
CMS_STAGE_GUARANTEE
CMS_STAGE_PROPERTY
CMS_STAGE_INSURANCE_POLICY
CMS_STAGE_ASSET_AIRCRAFT
CMS_STAGE_ASSET_GOLD
CMS_STAGE_ASSET_PDC
CMS_STAGE_ASSET_PLANT_EQUIP
STAGE_ASSET_TRADE_IN
CMS_STAGE_ASSET_VEHICLE
CMS_STAGE_ASSET_VESSEL
STAGE_CHECKLIST
STAGE_CHECKLIST_ITEM
cms_stage_cust_doc
cms_stage_cust_doc_item
sci_lsp_appr_lmts

-- composing
INSERT INTO HK_CMS_SECURITY 
SELECT * FROM CMS_SECURITY 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_cms_cash_deposit  
SELECT * FROM cms_cash_deposit  
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_sci_sec_pldgr_map 
SELECT * FROM sci_sec_pldgr_map 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_cms_ca_collateral_map 
SELECT * FROM cms_ca_collateral_map 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_CHARGE_DETAIL 
SELECT * FROM CMS_CHARGE_DETAIL 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_LIMIT_CHARGE_MAP  
SELECT * FROM CMS_LIMIT_CHARGE_MAP  
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_cms_limit_security_map 
SELECT * FROM cms_limit_security_map 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_ASSET 
SELECT * FROM CMS_ASSET 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_CASH 
SELECT * FROM CMS_CASH 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_ASSET_PDC 
SELECT * FROM CMS_ASSET_PDC 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_VALUATION 
SELECT * FROM CMS_VALUATION 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_INSURANCE 
SELECT * FROM CMS_INSURANCE 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_INSURANCE_CDS 
SELECT * FROM CMS_INSURANCE_CDS 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_MARKETABLE_SEC 
SELECT * FROM CMS_MARKETABLE_SEC 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_PORTFOLIO_ITEM 
SELECT * FROM CMS_PORTFOLIO_ITEM 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_DOCUMENT 
SELECT * FROM CMS_DOCUMENT 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_OTHERS 
SELECT * FROM CMS_OTHERS 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_GUARANTEE 
SELECT * FROM CMS_GUARANTEE 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_PROPERTY 
SELECT * FROM CMS_PROPERTY 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_INSURANCE_POLICY 
SELECT * FROM CMS_INSURANCE_POLICY 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_ASSET_AIRCRAFT 
SELECT * FROM CMS_ASSET_AIRCRAFT 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_ASSET_GOLD 
SELECT * FROM CMS_ASSET_GOLD 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_ASSET_PLANT_EQUIP 
SELECT * FROM CMS_ASSET_PLANT_EQUIP 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_ASSET_TRADE_IN 
SELECT * FROM CMS_ASSET_TRADE_IN 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_ASSET_VEHICLE 
SELECT * FROM CMS_ASSET_VEHICLE 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_ASSET_VESSEL 
SELECT * FROM CMS_ASSET_VESSEL 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_cms_checklist 
SELECT * FROM cms_checklist 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

    -- INSERT ROUND 1

    INSERT INTO HK_cms_checklist_item 
    SELECT * FROM cms_checklist_item 
    WHERE CHECKLIST_ID IN ( SELECT CHECKLIST_ID FROM CMS_CHECKLIST WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids))) ;

    INSERT INTO HK_cms_cust_doc 
    SELECT * FROM cms_cust_doc 
    WHERE CHECKLIST_ID IN ( SELECT CHECKLIST_ID FROM CMS_CHECKLIST WHERE CMS_COLLATERAL_ID IN  (SELECT * FROM TABLE(p_col_ids))) ;

    INSERT INTO HK_cms_cust_doc_item 
    SELECT * FROM cms_cust_doc_item 
    WHERE CUSTODIAN_DOC_ID IN (
        SELECT CUSTODIAN_DOC_ID FROM cms_cust_doc 
        WHERE CHECKLIST_ID IN ( SELECT CHECKLIST_ID FROM CMS_CHECKLIST WHERE CMS_COLLATERAL_ID IN  (SELECT * FROM TABLE(p_col_ids))) ;
    ) ;

CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

-- INSERT INTO HK_TRANSACTION 
-- SELECT * FROM TRANSACTION 
-- WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

-- INSERT INTO HK_TRANS_HISTORY 
-- SELECT * FROM TRANS_HISTORY 
-- WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

--STAGE
INSERT INTO HK_CMS_STAGE_SECURITY 
SELECT * FROM CMS_STAGE_SECURITY 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_STAGE_cash_deposit  
SELECT * FROM CMS_STAGE_cash_deposit  
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_STAGE_CHARGE_DETAIL 
SELECT * FROM CMS_STAGE_CHARGE_DETAIL 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_STAGE_LIMIT_CHARGE_MAP  
SELECT * FROM CMS_STAGE_LIMIT_CHARGE_MAP  
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_STAGE_limit_security_map 
SELECT * FROM CMS_STAGE_limit_security_map 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_STAGE_ASSET 
SELECT * FROM CMS_STAGE_ASSET 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_STAGE_CASH 
SELECT * FROM CMS_STAGE_CASH 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_STAGE_ASSET_PDC 
SELECT * FROM CMS_STAGE_ASSET_PDC 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_STAGE_VALUATION 
SELECT * FROM CMS_STAGE_VALUATION 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_STAGE_INSURANCE 
SELECT * FROM CMS_STAGE_INSURANCE 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_STAGE_INSURANCE_CDS 
SELECT * FROM CMS_STAGE_INSURANCE_CDS 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_STAGE_MARKETABLE_SEC 
SELECT * FROM CMS_STAGE_MARKETABLE_SEC 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_STAGE_PORTFOLIO_ITEM 
SELECT * FROM CMS_STAGE_PORTFOLIO_ITEM 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_STAGE_DOCUMENT 
SELECT * FROM CMS_STAGE_DOCUMENT 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_STAGE_OTHERS 
SELECT * FROM CMS_STAGE_OTHERS 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_STAGE_GUARANTEE 
SELECT * FROM CMS_STAGE_GUARANTEE 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_STAGE_PROPERTY 
SELECT * FROM CMS_STAGE_PROPERTY 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_STAGE_INSURANCE_POLICY 
SELECT * FROM CMS_STAGE_INSURANCE_POLICY 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_STAGE_ASSET_AIRCRAFT 
SELECT * FROM CMS_STAGE_ASSET_AIRCRAFT 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_STAGE_ASSET_GOLD 
SELECT * FROM CMS_STAGE_ASSET_GOLD 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;


INSERT INTO HK_CMS_STAGE_ASSET_PLANT_EQUIP 
SELECT * FROM CMS_STAGE_ASSET_PLANT_EQUIP 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_STAGE_ASSET_TRADE_IN 
SELECT * FROM STAGE_ASSET_TRADE_IN 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_STAGE_ASSET_VEHICLE 
SELECT * FROM CMS_STAGE_ASSET_VEHICLE 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_CMS_STAGE_ASSET_VESSEL 
SELECT * FROM CMS_STAGE_ASSET_VESSEL 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

INSERT INTO HK_STAGE_CHECKLIST 
SELECT * FROM STAGE_CHECKLIST 
WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

--round 2 stage

    INSERT INTO HK_STAGE_CHECKLIST_ITEM 
    SELECT * FROM STAGE_CHECKLIST_ITEM 
    WHERE CHECKLIST_ID IN ( SELECT CHECKLIST_ID FROM STAGE_CHECKLIST WHERE CMS_COLLATERAL_ID IN  (SELECT * FROM TABLE(p_col_ids))) ;

    INSERT INTO HK_cms_stage_cust_doc 
    SELECT * FROM cms_stage_cust_doc 
    WHERE CHECKLIST_ID IN ( SELECT CHECKLIST_ID FROM STAGE_CHECKLIST WHERE CMS_COLLATERAL_ID IN  (SELECT * FROM TABLE(p_col_ids))) ;

    INSERT INTO HK_cms_stage_cust_doc_item 
    SELECT * FROM cms_stage_cust_doc_item 
    WHERE CUSTODIAN_DOC_ID IN (
        SELECT CUSTODIAN_DOC_ID FROM cms_stage_cust_doc 
        WHERE CHECKLIST_ID IN ( SELECT CHECKLIST_ID FROM STAGE_CHECKLIST WHERE CMS_COLLATERAL_ID IN  (SELECT * FROM TABLE(p_col_ids))) ;
    ) ;

-- special TABLE
INSERT INTO HK_sci_lsp_appr_lmts		 
SELECT * FROM sci_lsp_appr_lmts 
WHERE CMS_LSP_APPR_LMTS_ID IN ( 
    SELECT CMS_LSP_APPR_LMTS_ID 
    FROM CMS_LIMIT_CHARGE_MAP
    WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids))
) ;


--DELETE 
DELETE FROM CMS_SECURITY WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM cms_cash_deposit  WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM sci_sec_pldgr_map WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM cms_ca_collateral_map WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_CHARGE_DETAIL WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_LIMIT_CHARGE_MAP  WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM cms_limit_security_map WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_ASSET WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_CASH WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_ASSET_PDC WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_VALUATION WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_INSURANCE WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_INSURANCE_CDS WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_MARKETABLE_SEC WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_PORTFOLIO_ITEM WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_DOCUMENT WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_OTHERS WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_GUARANTEE WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_PROPERTY WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_INSURANCE_POLICY WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_ASSET_AIRCRAFT WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_ASSET_GOLD WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_ASSET_PLANT_EQUIP WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_ASSET_TRADE_IN WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_ASSET_VEHICLE WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_ASSET_VESSEL WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM cms_checklist WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
    --delete round 1
DELETE FROM cms_checklist_item WHERE CHECKLIST_ID IN ( SELECT CHECKLIST_ID FROM CMS_CHECKLIST WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids))) ;
DELETE FROM cms_cust_doc WHERE CHECKLIST_ID IN ( SELECT CHECKLIST_ID FROM CMS_CHECKLIST WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids))) ;
DELETE FROM cms_cust_doc_item WHERE CUSTODIAN_DOC_ID IN (
    SELECT CUSTODIAN_DOC_ID FROM cms_cust_doc 
    WHERE CHECKLIST_ID IN ( SELECT CHECKLIST_ID FROM CMS_CHECKLIST WHERE CMS_COLLATERAL_ID IN  (SELECT * FROM TABLE(p_col_ids))) ;
) ;

DELETE FROM sci_lsp_appr_lmts WHERE CMS_LSP_APPR_LMTS_ID IN ( 
    SELECT CMS_LSP_APPR_LMTS_ID 
    FROM CMS_LIMIT_CHARGE_MAP
    WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids))
) ;


-- DELETE FROM cms_checklist_item WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
-- DELETE FROM cms_cust_doc WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
-- DELETE FROM cms_cust_doc_item WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
-- DELETE FROM TRANSACTION WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
-- DELETE FROM TRANS_HISTORY WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));

-- DELETE FROM CMS_STG_FACILITY_MASTER WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
-- DELETE FROM CMS_STG_FAC_RELATIONSHIP  WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
-- DELETE FROM CMS_STG_FAC_MULTI_TIER_FINANCI WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
-- DELETE FROM CMS_STG_FAC_PREPAYMENT_LIST WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
-- DELETE FROM CMS_STG_FAC_REDUCTION_SCHEDULE WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
-- DELETE FROM CMS_STG_LSP_APPR_DRAWING_CURR WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
-- DELETE FROM CMS_STG_FAC_MESSAGE WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
-- DELETE FROM CMS_STG_FAC_INCREMENTAL WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
-- DELETE FROM CMS_STG_FAC_REDUCTION_SCHEDULE WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
-- DELETE FROM CMS_STG_FAC_GENERAL  WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
-- DELETE FROM CMS_STG_FAC_INTEREST WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
-- DELETE FROM CMS_STG_FAC_ADDITIONAL WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
-- DELETE FROM CMS_STG_FAC_FEE_CHARGE WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
-- DELETE FROM CMS_STG_FAC_BNM_CODES WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
-- DELETE FROM CMS_STG_FAC_ISLAMIC_MASTER WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
-- DELETE FROM CMS_STG_FAC_BBA_VARI_PACKAGE WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
-- DELETE FROM CMS_STG_FAC_RENTAL_RENEWAL WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
-- DELETE FROM CMS_STG_FAC_SECURITY_DEPOSIT WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
-- DELETE FROM CMS_STG_FAC_TSPR WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));

DELETE FROM CMS_STAGE_SECURITY WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_STAGE_cash_deposit  WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_STAGE_CHARGE_DETAIL WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_STAGE_LIMIT_CHARGE_MAP  WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_STAGE_limit_security_map WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_STAGE_ASSET WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_STAGE_CASH WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_STAGE_ASSET_PDC WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_STAGE_VALUATION WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_STAGE_INSURANCE WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_STAGE_INSURANCE_CDS WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_STAGE_MARKETABLE_SEC WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_STAGE_PORTFOLIO_ITEM WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_STAGE_DOCUMENT WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_STAGE_OTHERS WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_STAGE_GUARANTEE WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_STAGE_PROPERTY WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_STAGE_INSURANCE_POLICY WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_STAGE_ASSET_AIRCRAFT WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_STAGE_ASSET_GOLD WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_STAGE_ASSET_PLANT_EQUIP WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM STAGE_ASSET_TRADE_IN WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_STAGE_ASSET_VEHICLE WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM CMS_STAGE_ASSET_VESSEL WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
DELETE FROM STAGE_CHECKLIST WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
-- DELETE FROM STAGE_CHECKLIST_ITEM WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
-- DELETE FROM cms_stage_cust_doc WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
-- DELETE FROM cms_stage_cust_doc_item WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));

--DELETE round 2 stage

    DELETE FROM STAGE_CHECKLIST_ITEM 
    WHERE CHECKLIST_ID IN ( SELECT CHECKLIST_ID FROM STAGE_CHECKLIST WHERE CMS_COLLATERAL_ID IN  (SELECT * FROM TABLE(p_col_ids))) ;

    DELETE FROM cms_stage_cust_doc 
    WHERE CHECKLIST_ID IN ( SELECT CHECKLIST_ID FROM STAGE_CHECKLIST WHERE CMS_COLLATERAL_ID IN  (SELECT * FROM TABLE(p_col_ids))) ;

    DELETE FROM cms_stage_cust_doc_item 
    WHERE CUSTODIAN_DOC_ID IN (
        SELECT CUSTODIAN_DOC_ID FROM cms_stage_cust_doc 
        WHERE CHECKLIST_ID IN ( SELECT CHECKLIST_ID FROM STAGE_CHECKLIST WHERE CMS_COLLATERAL_ID IN  (SELECT * FROM TABLE(p_col_ids))) ;
    ) ;

    623
    753
    793
    841
    

