--Search unique
SELECT * FROM SCI_SEC_PLDGR_MAP WHERE CMS_PLEDGOR_DTL_ID =  20220726041943394;

--delete
DELETE FROM CMS_SECURITY WHERE CMS_COLLATERAL_ID IN ( 20220726020559087, 20220726020559085);
DELETE FROM CMS_ASSET WHERE CMS_COLLATERAL_ID IN ( 20220726020559087, 20220726020559085);
DELETE FROM SCI_PLEDGOR_DTL WHERE CMS_PLEDGOR_DTL_ID =  20220726041943394;
DELETE FROM SCI_SEC_PLDGR_MAP WHERE CMS_SEC_PLDGR_MAP_ID = 20220726041943395; 
COMMIT;

ROLLBACK;


SELECT * FROM SCI_SEC_PLDGR_MAP WHERE CMS_PLEDGOR_DTL_ID =  20220726041943394;

--find table Sec_subtype
SELECT * FROM user_tables where table_name like '%ASSET%';
SELECT * FROM user_tables where table_name like '%CASH%';

DELETE FROM CMS_SECURITY WHERE CMS_COLLATERAL_ID IN ( 20220726020559087, 20220726020559085);
DELETE FROM CMS_ASSET WHERE CMS_COLLATERAL_ID IN ( 20220726020559087, 20220726020559085);
DELETE FROM SCI_PLEDGOR_DTL WHERE CMS_PLEDGOR_DTL_ID =  20220726041943394;
DELETE FROM SCI_SEC_PLDGR_MAP WHERE CMS_SEC_PLDGR_MAP_ID = 20220726041943395; 

SELECT * FROM user_tables where table_name like '%ASSET%';
SELECT * FROM CMS_ASSET_VEHICLE WHERE cms_collateral_id IN (20220726020559087, 20220726020559085) ;

SELECT * FROM CMS_STAGE_ASSET_VEHICLE WHERE cms_collateral_id IN (20220726020559087, 20220726020559085) ;

SELECT* FROM CMS_SECURITY_SUB_TYPE;

-- add thí for case 1438
SELECT * FROM CMS_ASSET_VEHICLE WHERE cms_collateral_id IN (20220726020559087, 20220726020559085) ;

--send for case 1434
-- SELECT * FROM CMS_SECURITY WHERE LOS_SECURITY_DTL_ID IN( 202205250022068591 );

--SELECT ALL INFORMATION RELATED TO CHECKLIST
SELECT * FROM cms_checklist 
JOIN cms_security ON cms_checklist.cms_collateral_id  = cms_security.cms_collateral_id 
WHERE cms_security.CMS_COLLATERAL_ID IN (SELECT CMS_COLLATERAL_ID FROM CMS_SECURITY WHERE LOS_SECURITY_DTL_ID = 202205250022068591 ) ;

SELECT * FROM CMS_CHECKLIST_ITEM WHERE CHECKLIST_ID = (SELECT CHECKLIST_ID FROM cms_checklist 
JOIN cms_security ON cms_checklist.cms_collateral_id  = cms_security.cms_collateral_id 
WHERE cms_security.CMS_COLLATERAL_ID IN (SELECT CMS_COLLATERAL_ID FROM CMS_SECURITY WHERE LOS_SECURITY_DTL_ID = 202205250022068591 )) ;

SELECT * FROM CMS_CA_COLLATERAL_MAP cc WHERE CC.CMS_COLLATERAL_ID IN (SELECT CMS_COLLATERAL_ID FROM CMS_SECURITY WHERE LOS_SECURITY_DTL_ID = 202205250022068591 ) ;

SELECT lm.* 
from sci_lsp_lmt_profile lm , CMS_CA_COLLATERAL_MAP map
where LM.CMS_LSP_LMT_PROFILE_ID = map.CMS_LSP_LMT_PROFILE_ID
AND map.CMS_COLLATERAL_ID IN (SELECT CMS_COLLATERAL_ID FROM CMS_SECURITY WHERE LOS_SECURITY_DTL_ID = 202205250022068591 ) ;

SELECT * FROM CMS_ASSET WHERE cms_asset.CMS_COLLATERAL_ID IN (SELECT CMS_COLLATERAL_ID FROM CMS_SECURITY WHERE LOS_SECURITY_DTL_ID = 202205250022068591 );

SELECT * FROM CMS_CHARGE_DETAIL chrg WHERE chrg.CMS_COLLATERAL_ID IN (SELECT CMS_COLLATERAL_ID FROM CMS_SECURITY WHERE LOS_SECURITY_DTL_ID = 202205250022068591 ) ;

SELECT * FROM CMS_FAC_RELATIONSHIP fac, CMS_CHARGE_DETAIL cd
WHERE fac.CMS_REF_ID = cd.CMS_REF_ID
AND cd.CMS_COLLATERAL_ID IN (SELECT CMS_COLLATERAL_ID FROM CMS_SECURITY WHERE LOS_SECURITY_DTL_ID = 202205250022068591 ) ;

SELECT * FROM cms_facility_master fm
LEFT JOIN CMS_FAC_RELATIONSHIP fac
ON fm.ID = fac.CMS_FAC_MASTER_ID
JOIN CMS_CHARGE_DETAIL cd
ON fac.CMS_REF_ID = cd.CMS_REF_ID
AND cd.CMS_COLLATERAL_ID IN (SELECT CMS_COLLATERAL_ID FROM CMS_SECURITY WHERE LOS_SECURITY_DTL_ID = 202205250022068591 ) ;

SELECT * FROM CMS_LIMIT_CHARGE_MAP CM, CMS_CHARGE_DETAIL C 
WHERE C.CMS_COLLATERAL_ID IN (SELECT CMS_COLLATERAL_ID FROM CMS_SECURITY WHERE LOS_SECURITY_DTL_ID = 202205250022068591 ) AND
C.CHARGE_DETAIL_ID = CM.CHARGE_DETAIL_ID;

SELECT * FROM CMS_LIMIT_SECURITY_MAP lsm WHERE lsm.CMS_COLLATERAL_ID IN (SELECT CMS_COLLATERAL_ID FROM CMS_SECURITY WHERE LOS_SECURITY_DTL_ID = 202205250022068591 ) ;

SELECT lmt.* FROM SCI_LSP_APPR_LMTS lmt, CMS_LIMIT_SECURITY_MAP lsm
WHERE lmt.CMS_LSP_APPR_LMTS_ID = lsm.CMS_LSP_APPR_LMTS_ID
AND lsm.CMS_COLLATERAL_ID IN (SELECT CMS_COLLATERAL_ID FROM CMS_SECURITY WHERE LOS_SECURITY_DTL_ID = 202205250022068591 ) ;

SELECT cms_cust_doc.* FROM   cms_checklist  
LEFT OUTER JOIN  cms_cust_doc  ON  cms_checklist.checklist_id  = cms_cust_doc.checklist_id    
JOIN cms_security ON cms_checklist.cms_collateral_id  = cms_security.cms_collateral_id 
WHERE cms_security.CMS_COLLATERAL_ID IN (SELECT CMS_COLLATERAL_ID FROM CMS_SECURITY WHERE LOS_SECURITY_DTL_ID = 202205250022068591 ) ;


SELECT cms_cust_doc_item.* FROM   cms_checklist  
LEFT OUTER JOIN  cms_cust_doc  ON  cms_checklist.checklist_id  = cms_cust_doc.checklist_id   
LEFT OUTER JOIN  cms_cust_doc_item ON cms_cust_doc_item.CUSTODIAN_DOC_ID = cms_cust_doc.CUSTODIAN_DOC_ID
JOIN cms_security ON cms_checklist.cms_collateral_id  = cms_security.cms_collateral_id 
WHERE cms_security.CMS_COLLATERAL_ID IN (SELECT CMS_COLLATERAL_ID FROM CMS_SECURITY WHERE LOS_SECURITY_DTL_ID = 202205250022068591 ) ;


SELECT sci_le_sub_profile.* FROM   cms_checklist  
LEFT OUTER JOIN  cms_cust_doc  ON  cms_checklist.checklist_id  = cms_cust_doc.checklist_id    
LEFT OUTER JOIN  sci_le_sub_profile  ON  sci_le_sub_profile.CMS_LE_SUB_PROFILE_ID  = cms_checklist.CMS_LMP_SUB_PROFILE_ID   
JOIN cms_security ON cms_checklist.cms_collateral_id  = cms_security.cms_collateral_id 
WHERE cms_security.CMS_COLLATERAL_ID IN (SELECT CMS_COLLATERAL_ID FROM CMS_SECURITY WHERE LOS_SECURITY_DTL_ID = 202205250022068591 ) ;

SELECT sci_le_main_profile.*  FROM  cms_checklist  
LEFT OUTER JOIN  cms_cust_doc  ON  cms_checklist.checklist_id  = cms_cust_doc.checklist_id    
LEFT OUTER JOIN  sci_le_sub_profile  ON  sci_le_sub_profile.CMS_LE_SUB_PROFILE_ID  = cms_checklist.CMS_LMP_SUB_PROFILE_ID   
LEFT OUTER JOIN  sci_le_main_profile  ON  sci_le_main_profile.CMS_LE_MAIN_PROFILE_ID  =sci_le_sub_profile.CMS_LE_MAIN_PROFILE_ID
JOIN cms_security ON cms_checklist.cms_collateral_id  = cms_security.cms_collateral_id 
WHERE cms_security.CMS_COLLATERAL_ID IN (SELECT CMS_COLLATERAL_ID FROM CMS_SECURITY WHERE LOS_SECURITY_DTL_ID = 202205250022068591 ) ;


SELECT SCI_PLEDGOR_DTL.* 
FROM SCI_PLEDGOR_DTL, SCI_SEC_PLDGR_MAP, CMS_SECURITY
WHERE SCI_PLEDGOR_DTL.CMS_PLEDGOR_DTL_ID = SCI_SEC_PLDGR_MAP.CMS_PLEDGOR_DTL_ID 
AND SCI_SEC_PLDGR_MAP.CMS_COLLATERAL_ID = CMS_SECURITY.CMS_COLLATERAL_ID 
AND cms_security.CMS_COLLATERAL_ID IN (SELECT CMS_COLLATERAL_ID FROM CMS_SECURITY WHERE LOS_SECURITY_DTL_ID = 202205250022068591 ) ;

SELECT SCI_SEC_PLDGR_MAP.*
FROM SCI_PLEDGOR_DTL, SCI_SEC_PLDGR_MAP, CMS_SECURITY
WHERE SCI_PLEDGOR_DTL.CMS_PLEDGOR_DTL_ID = SCI_SEC_PLDGR_MAP.CMS_PLEDGOR_DTL_ID 
	AND SCI_SEC_PLDGR_MAP.CMS_COLLATERAL_ID = CMS_SECURITY.CMS_COLLATERAL_ID 
	AND cms_security.CMS_COLLATERAL_ID IN (SELECT CMS_COLLATERAL_ID FROM CMS_SECURITY WHERE LOS_SECURITY_DTL_ID = 202205250022068591 ) ;

--asset Table:
SELECT * FROM CMS_CASH WHERE CMS_COLLATERAL_ID IN (SELECT CMS_COLLATERAL_ID FROM CMS_SECURITY WHERE LOS_SECURITY_DTL_ID = 202205250022068591);
SELECT * FROM CMS_CASH_DEPOSIT WHERE CMS_COLLATERAL_ID IN (SELECT CMS_COLLATERAL_ID FROM CMS_SECURITY WHERE LOS_SECURITY_DTL_ID = 202205250022068591);
SELECT * FROM CMS_CASH_MARGIN WHERE CMS_COLLATERAL_ID IN (SELECT CMS_COLLATERAL_ID FROM CMS_SECURITY WHERE LOS_SECURITY_DTL_ID = 202205250022068591);
SELECT * FROM CMS_DEAL_CASH WHERE CMS_COLLATERAL_ID IN (SELECT CMS_COLLATERAL_ID FROM CMS_SECURITY WHERE LOS_SECURITY_DTL_ID = 202205250022068591);



-- TYPE OF COL TSĐB
protected static final String QUERY = "SELECT SECURITY_SUB_TYPE_ID,NET_REALIZABLE_VALUE,SCI_ORIG_SECURITY_CURRENCY, "
			+ "CMV,CMV_CURRENCY,FSV,FSV_CURRENCY,SCI_SECURITY_CURRENCY,CMS_COLLATERAL_ID,RESERVE_PRICE "
			+ "FROM CMS_SECURITY " + "WHERE ( SCI_SECURITY_TYPE_VALUE='PT' " + "OR SCI_SECURITY_TYPE_VALUE='MS' "
			+ "OR SCI_SECURITY_TYPE_VALUE='DC' " + "OR SCI_SECURITY_TYPE_VALUE='AB' "
			+ "OR SCI_SECURITY_TYPE_VALUE='CL' " + "OR SCI_SECURITY_TYPE_VALUE='CS' "
			+ "OR SCI_SECURITY_TYPE_VALUE='GT' " + "OR SCI_SECURITY_TYPE_VALUE='IN' "
			+ "OR SCI_SECURITY_TYPE_VALUE='OT' ) " + "AND DAYS(LAST_REMARGIN_DATE) = DAYS(CURRENT TIMESTAMP) ";

			