SELECT * FROM SML_CA WHERE CA_NUMBER LIKE '%CAR/22/9002/00600/05156850%' ;

SELECT SEC.ID, A.CA_ID, SEC.COLLATERAL_DESCRIPTION, B.EXPRESSED_CONDITION, B.PROPERTY_ADDRESS,
  SEC.*,
  A.*
FROM SML_SECURITY SEC
LEFT JOIN sml_ca_collateral A ON SEC.ID = A.COLLATERAL_ID
LEFT JOIN SML_SEC_PT B ON SEC.ID= B.ID
WHERE
A.CA_ID IN ( SELECT ID FROM SML_CA WHERE CA_NUMBER LIKE '%CAR/22/9002/00600/05156850%') ; 

PHY_INSPECT_FREQ_UNIT   
STD_QUIT_RENT
NON_STD_QUIT_RENT
QUIT_RENT_RECEIPT
ASSESSMENT
MASTER_TITLE
MASTER_TITLE_NUMBER
INSURANCE
AUTO_DEBIT
REAL_ESTATE_WITH_RENTAL_FLAG
PROPERTY_COMPLETION_STATUS
REDUCED_RISK_WEIGHT_FLAG
PROPERTY_COMPLETED_FLAG
PROPERTY_WELL_DEVELOPED_FLAG
METHODOLOGY_FOR_VALUATION_FLAG
BREACH_IND
ASSUMPTION
VENDOR_RELATED_BORROWER_IND
VAL_REPORT_ADD_IND
VAL_REPORT_REVIEWED_IND

SELECT SEC.ID, A.CA_ID, 
    B.Title_Number_prefix, rawtohex(B.Title_Number_prefix),
    B. Lot_No, rawtohex(Lot_No),
    B.Lot_Number_prefix, rawtohex(Lot_Number_prefix), 
    B.postcode, rawtohex(postcode),
    B.Phy_inspect_freq_unit, rawtohex(Phy_inspect_freq_unit),
    B.Property_Address, rawtohex(Property_Address),
    B.Assessment, rawtohex(Assessment),
    B.district, rawtohex(district),
    B.ABANDONED_PROJECT, rawtohex(ABANDONED_PROJECT),
    B.INDEPENDENT_VALUER_FLAG, rawtohex(INDEPENDENT_VALUER_FLAG),
    B.PROJECT_NAME, rawtohex(PROJECT_NAME),
	B.NON_PREFERRED_LOCATION, rawtohex(NON_PREFERRED_LOCATION),
    B.property_completion_stage, rawtohex(property_completion_stage),
    B.scheduled_location, rawtohex(scheduled_location),
    B.MORTGAGE_TYPE, rawtohex(MORTGAGE_TYPE),
    B.TENANT_TYPE, rawtohex(TENANT_TYPE),
    SEC.EXCHANGE_CONTROL_OBTAINED, rawtohex(EXCHANGE_CONTROL_OBTAINED),
    SEC.SCI_REFERENCE_NOTE,rawtohex(SCI_REFERENCE_NOTE),
    SEC.SCI_SECURITY_CCY, rawtohex(SCI_SECURITY_CCY),
    SEC.SOURCE_ID, rawtohex(SEC.SOURCE_ID),
    SEC.COLLATERAL_DESCRIPTION, rawtohex(SEC.COLLATERAL_DESCRIPTION),
    SEC.COLLATERAL_NAME,rawtohex(SEC.COLLATERAL_NAME),
	SEC.ASSESSMENT_OF_COLLATERAL,rawtohex(SEC.ASSESSMENT_OF_COLLATERAL)
FROM 
SML_SECURITY SEC
LEFT JOIN sml_ca_collateral A ON SEC.ID = A.COLLATERAL_ID 
LEFT JOIN SML_SEC_PT B ON SEC.ID= B.ID 
LEFT JOIN sml_pledgor C ON C.COLLATERAL_ID = SEC.ID
LEFT JOIN sml_customer D ON D.ID = C.owner_id
LEFT JOIN SML_SEC_VALUATION E ON E.Collateral_id = sec.id 
WHERE A.CA_ID IN ( SELECT ID FROM SML_CA WHERE CA_NUMBER LIKE '%CAR/22/9002/00600/05156850%');


SELECT B.*
FROM SML_SECURITY SEC
LEFT JOIN sml_ca_collateral A ON SEC.ID = A.COLLATERAL_ID
LEFT JOIN SML_SEC_PT B ON SEC.ID= B.ID
WHERE
A.CA_ID IN ( SELECT ID FROM SML_CA WHERE CA_NUMBER LIKE '%CAR/22/9002/00600/05156850%') ; 

PHY_INSPECT_FREQ_UNIT   
STD_QUIT_RENT
NON_STD_QUIT_RENT
QUIT_RENT_RECEIPT
ASSESSMENT
MASTER_TITLE
MASTER_TITLE_NUMBER
INSURANCE
AUTO_DEBIT
REAL_ESTATE_WITH_RENTAL_FLAG
PROPERTY_COMPLETION_STATUS
REDUCED_RISK_WEIGHT_FLAG
PROPERTY_COMPLETED_FLAG
PROPERTY_WELL_DEVELOPED_FLAG
METHODOLOGY_FOR_VALUATION_FLAG
BREACH_IND
ASSUMPTION
VENDOR_RELATED_BORROWER_IND
VAL_REPORT_ADD_IND
VAL_REPORT_REVIEWED_IND

SELECT SEC.ID, A.CA_ID, 
    SEC.CMV_CCY, rawtohex(SEC.CMV_CCY),
    SEC.STATUS, rawtohex(SEC.STATUS),
    SEC.CUSTODIAN_TYPE, rawtohex(SEC.CUSTODIAN_TYPE),
    SEC.BASE_COLL_ID, rawtohex(SEC.BASE_COLL_ID),
    SEC.BOA_IND, rawtohex(SEC.BOA_IND),
    B.ENV_RISKY_STATUS, rawtohex(B.ENV_RISKY_STATUS),
    B.IS_PHY_INSPECT, rawtohex(IS_PHY_INSPECT),
    B.TENURE_UNIT, rawtohex(TENURE_UNIT),
    B.REMAIN_TENURE_UNIT, rawtohex(REMAIN_TENURE_UNIT),
    B.INSURABLE_CCY, rawtohex(INSURABLE_CCY), 
    B.INSURED_CCY, rawtohex(B.INSURED_CCY), --CUT
    B.PHY_INSPECT_FREQ_UNIT, rawtohex(PHY_INSPECT_FREQ_UNIT),
    B.STD_QUIT_RENT, rawtohex(STD_QUIT_RENT),
    B.ASSESSMENT, rawtohex(ASSESSMENT),
    B.MASTER_TITLE, rawtohex(MASTER_TITLE),
    B.MASTER_TITLE_NUMBER, rawtohex(B.MASTER_TITLE_NUMBER),
    B.INSURANCE, rawtohex(INSURANCE),
    B.AUTO_DEBIT, rawtohex(AUTO_DEBIT),
    B.REAL_ESTATE_WITH_RENTAL_FLAG, rawtohex(REAL_ESTATE_WITH_RENTAL_FLAG),
    B.PROPERTY_COMPLETION_STATUS, rawtohex(PROPERTY_COMPLETION_STATUS),
    B.PROPERTY_COMPLETED_FLAG, rawtohex(B.PROPERTY_COMPLETED_FLAG),
    B.PROPERTY_WELL_DEVELOPED_FLAG, rawtohex(PROPERTY_WELL_DEVELOPED_FLAG),
    B.METHODOLOGY_FOR_VALUATION_FLAG, rawtohex(METHODOLOGY_FOR_VALUATION_FLAG),
    B.BREACH_IND, rawtohex(BREACH_IND),
    B.ASSUMPTION, rawtohex(ASSUMPTION),
    B.VENDOR_RELATED_BORROWER_IND, rawtohex(VENDOR_RELATED_BORROWER_IND),
    B.VAL_REPORT_ADD_IND, rawtohex(VAL_REPORT_ADD_IND),
    B.VAL_REPORT_REVIEWED_IND, rawtohex(VAL_REPORT_REVIEWED_IND)
FROM 
SML_SECURITY SEC
LEFT JOIN sml_ca_collateral A ON SEC.ID = A.COLLATERAL_ID 
LEFT JOIN SML_SEC_PT B ON SEC.ID= B.ID 
LEFT JOIN sml_pledgor C ON C.COLLATERAL_ID = SEC.ID
LEFT JOIN sml_customer D ON D.ID = C.owner_id
LEFT JOIN SML_SEC_VALUATION E ON E.Collateral_id = sec.id 
WHERE A.CA_ID IN ( SELECT ID FROM SML_CA WHERE CA_NUMBER LIKE '%CAR/22/9002/00600/05156850%');


-- FIELD ERROR ADDITIONAL
REAL_ESTATE_WITH_RENTAL_FLAG, PROPERTY_COMPLETED_FLAG, PROPERTY_WELL_DEVELOPED_FLAG, METHODOLOGY_FOR_VALUATION_FLAG, BREACH_IND

PROPERTY_COMPLETION_STATUS, 


SELECT SEC.ID, B.ID,
    B.ABANDONED_PROJECT, rawtohex(ABANDONED_PROJECT),
    B.INDEPENDENT_VALUER_FLAG, rawtohex(INDEPENDENT_VALUER_FLAG)
FROM SML_SECURITY SEC
LEFT JOIN SML_SEC_PT B ON SEC.ID= B.ID 
where sec.collateral_no in ('PT202203100021469692', 'PT202205270022091584', 'PT202203100021469710', 'PT202205270022091653');

SELECT SEC.ID, B.ID,
    B.ABANDONED_PROJECT, rawtohex(ABANDONED_PROJECT),
    B.INDEPENDENT_VALUER_FLAG rawtohex(INDEPENDENT_VALUER_FLAG)
FROM SML_SECURITY SEC
LEFT JOIN SML_SEC_PT B ON SEC.ID= B.ID 
where sec.collateral_no in ('PT202203100021469692', 'PT202205270022091584', 'PT202203100021469710', 'PT202205270022091653');