-- REQUEST HOST ITG CA -> LOG
-- VCLOSPRODA 1439
SELECT * FROM SML_CA WHERE CA_NUMBER LIKE '%CAR/22/9001/00200/05103744%';

-- request Facs and cols, tsđb link với CA
-- VCLOSUAT 372
SELECT * FROM SML_CA WHERE CA_NUMBER LIKE '%CAR/22/9001/00343/01304212%';
SELECT * FROM SML_FACILITY FAC INNER JOIN SML_CA CA ON FAC.CA_ID = CA.ID AND CA. CA_NUMBER LIKE '%CAR/22/9001/00343/01304212%' ;

select caColl.*
from SML_CA_COLLATERAL caColl, SML_CA ca, SML_SECURITY sec
where caColl.CA_ID = ( SELECT ID FROM SML_CA WHERE CA_NUMBER LIKE '%CAR/22/9001/00343/01304212%') 
and caColl.CA_ID = ca.ID and caColl.COLLATERAL_ID = sec.ID;

select sec.*
from SML_CA_COLLATERAL caColl, SML_CA ca, SML_SECURITY sec
where caColl.CA_ID = ( SELECT ID FROM SML_CA WHERE CA_NUMBER LIKE '%CAR/22/9001/00343/01304212%') 
and caColl.CA_ID = ca.ID and caColl.COLLATERAL_ID = sec.ID;

SELECT CHARGE_FACILITY.* FROM SML_CHARGE_FACILITY_MAP CHARGE_FACILITY
INNER JOIN SML_FACILITY FAC ON CHARGE_FACILITY.FACILITY_ID = FAC.ID
-- INNER JOIN SML_CHARGE_DETAIL CHARGE ON CHARGE.ID = CHARGE_FACILITY.CHARGE_DETAIL_ID
-- INNER JOIN SML_SECURITY COL ON COL.ID = CHARGE.COLLATERAL_ID
-- INNER JOIN SML_CA_COLLATERAL CA_COL ON CA_COL.COLLATERAL_ID = COL.ID
-- INNER JOIN SML_CA CA ON CA.ID = CA_COL.CA_ID
AND FAC.CA_ID = ( SELECT ID FROM SML_CA WHERE CA_NUMBER LIKE '%CAR/22/9001/00343/01304212%') ;

SELECT CHARGE.* FROM SML_CHARGE_FACILITY_MAP CHARGE_FACILITY
INNER JOIN SML_FACILITY FAC ON CHARGE_FACILITY.FACILITY_ID = FAC.ID
INNER JOIN SML_CHARGE_DETAIL CHARGE ON CHARGE.ID = CHARGE_FACILITY.CHARGE_DETAIL_ID
-- INNER JOIN SML_SECURITY COL ON COL.ID = CHARGE.COLLATERAL_ID
-- INNER JOIN SML_CA_COLLATERAL CA_COL ON CA_COL.COLLATERAL_ID = COL.ID
-- INNER JOIN SML_CA CA ON CA.ID = CA_COL.CA_ID
AND FAC.CA_ID = ( SELECT ID FROM SML_CA WHERE CA_NUMBER LIKE '%CAR/22/9001/00343/01304212%') ;


-- VCLOSPRODA 1425
SELECT * FROM SML_CA WHERE CA_NUMBER LIKE '%CAR/22/9002/00640/04911059%';

SELECT * FROM SML_FACILITY FAC INNER JOIN SML_CA CA ON FAC.CA_ID = CA.ID AND CA. CA_NUMBER LIKE '%CAR/22/9002/00640/04911059%' ;

select caColl.*
from SML_CA_COLLATERAL caColl, SML_CA ca, SML_SECURITY sec
where caColl.CA_ID = ( SELECT ID FROM SML_CA WHERE CA_NUMBER LIKE '%CAR/22/9002/00640/04911059%') 
and caColl.CA_ID = ca.ID and caColl.COLLATERAL_ID = sec.ID;

select sec.*
from SML_CA_COLLATERAL caColl, SML_CA ca, SML_SECURITY sec
where caColl.CA_ID = ( SELECT ID FROM SML_CA WHERE CA_NUMBER LIKE '%CAR/22/9002/00640/04911059%') 
and caColl.CA_ID = ca.ID and caColl.COLLATERAL_ID = sec.ID;

SELECT CHARGE_FACILITY.* FROM SML_CHARGE_FACILITY_MAP CHARGE_FACILITY
INNER JOIN SML_FACILITY FAC ON CHARGE_FACILITY.FACILITY_ID = FAC.ID
AND FAC.CA_ID = ( SELECT ID FROM SML_CA WHERE CA_NUMBER LIKE '%CAR/22/9002/00640/04911059%') ;

SELECT CHARGE.* FROM SML_CHARGE_FACILITY_MAP CHARGE_FACILITY
INNER JOIN SML_FACILITY FAC ON CHARGE_FACILITY.FACILITY_ID = FAC.ID
INNER JOIN SML_CHARGE_DETAIL CHARGE ON CHARGE.ID = CHARGE_FACILITY.CHARGE_DETAIL_ID
AND FAC.CA_ID = ( SELECT ID FROM SML_CA WHERE CA_NUMBER LIKE '%CAR/22/9002/00640/04911059%') ;


-- ADD CHECK DOCUMENT ON 1425
SELECT doc.* FROM sml_doc doc WHERE doc.ca_id = ( SELECT ID FROM SML_CA WHERE CA_NUMBER LIKE '%CAR/22/9002/00640/04911059%') ;

-- INNER JOIN sml_customer cif
-- ON doc.los_cif_id = cif.id
-- AND doc.ca_id = ( SELECT ID FROM SML_CA WHERE CA_NUMBER LIKE '%CAR/22/9002/00640/04911059%') ;

-- SELECT * UNION
-- FROM    sml_doc doc
-- INNER JOIN sml_security coll
-- ON     doc.los_coll_id = coll.id
--         AND doc.ca_id = :ca_id_in
--         AND doc.checklist_type = :checklist_type_in;


--372 
select product.LOAN_TREASURY_TYPE from "
    		+ "sml_facility fac left join SML_PROD_PKG_PRODUCT pkproduct on fac.prod_pkg_product_id = pkproduct.id "
    		+ "left join SML_PRODUCT product on pkproduct.PRODUCT_ID = product.id "
    		+ "where fac.id=? 

            