-- SIT: rmqtrang001 pasword02

-- RLOS
-- VTB.RLOS.05


UPDATE SML_USER_AUTHENTICATION ua 
SET ua.LAST_UPDATE_DATE = SYSDATE,
    ua.LAST_LOGIN_TIME = SYSDATE,
    ua.LOGIN_ATTEMPTS = 0
WHERE ua.ID in (SELECT ID FROM SML_USER WHERE LOGIN_ID = '');

UPDATE SML_USER u 
SET u.LAST_UPDATE_DATE = SYSDATE,
    u.LAST_ACTIVATION_DATE = SYSDATE,
    u.ID_STATUS = 'A',
    u.ID_ACTIVATION_IND = 'A',
WHERE u.LOGIN_ID = '';

UPDATE SML_USER_PWD_HISTORY 
SET CREATION_DATE = SYSDATE;