SELECT CMS_COLLATERAL_ID FROM CMS_VALUATION WHERE valuation_date LIKE '%JAN-23%';

SELECT * FROM cms_valuation WHERE VALUATION_DATE IS NOT NULL ORDER BY valuation_date DESC;

--20-OCT-22
SELECT CMS_COLLATERAL_ID FROM CMS_VALUATION WHERE valuation_date LIKE '%OCT-22%';   

--count COLL
SELECT COUNT(1) 
FROM CMS_SECURITY S,
	CMS_SECURITY_PARAMETER P,
	TRANSACTION T
WHERE S.SECURITY_LOCATION = P.COUNTRY_ISO_CODE
	AND S.SECURITY_SUB_TYPE_ID = P.SECURITY_SUB_TYPE_ID
	AND S.CMS_COLLATERAL_ID = T.REFERENCE_ID
	AND T.TRANSACTION_TYPE = 'COL'
	AND T.STATUS NOT IN ('PENDING_UPDATE', 'PENDING_RETRY')
	AND P.STATUS = 'ACTIVE'  
	AND P.THRESHOLD_PERCENT IS NOT NULL
	AND P.VALUATION_FREQUENCY IS NOT NULL
	AND nvl(P.VALUATION_FREQUENCY, 0) > 0
	AND P.VALUATION_FREQUENCY_UNIT IS NOT NULL
	AND P.VALUATION_FREQUENCY_UNIT <> ' ' 
	AND (
		S.SECURITY_SUB_TYPE_ID NOT IN ('AB100', 'AB103', 'AB106', 'AB107', 'AB108', 'CL001')
		AND S.SECURITY_SUB_TYPE_ID NOT LIKE 'DC%'
	) AND (
		(NEXT_REMARGIN_DATE IS NULL)
		OR (
			NEXT_REMARGIN_DATE IS NOT NULL
			AND trunc(S.NEXT_REMARGIN_DATE) <= trunc(sysdate)
		)
	)
	AND (
		(VALUATED_DATE IS NULL)
		OR (
			VALUATED_DATE IS NOT NULL
			AND trunc(VALUATED_DATE) < trunc(sysdate)
		)
	) 
	AND S.STATUS = 'ACTIVE' ;

-- PICK COL
SELECT S.CMS_COLLATERAL_ID,
	VALUATED_DATE,
	S.SCI_SECURITY_DTL_ID,
	S.SCI_SECURITY_TYPE_VALUE,
	S.SCI_SECURITY_SUBTYPE_VALUE,
	S.SECURITY_LOCATION,
	S.SCI_SECURITY_TYPE_VALUE
FROM CMS_SECURITY S,
	CMS_SECURITY_PARAMETER P,
	TRANSACTION T
WHERE S.SECURITY_LOCATION = P.COUNTRY_ISO_CODE
	AND S.SECURITY_SUB_TYPE_ID = P.SECURITY_SUB_TYPE_ID
	AND S.CMS_COLLATERAL_ID = T.REFERENCE_ID
	AND T.TRANSACTION_TYPE = 'COL'
	AND T.STATUS NOT IN ('PENDING_UPDATE', 'PENDING_RETRY')
	AND P.STATUS = 'ACTIVE'  
	AND P.THRESHOLD_PERCENT IS NOT NULL
	AND P.VALUATION_FREQUENCY IS NOT NULL
	AND nvl(P.VALUATION_FREQUENCY, 0) > 0
	AND P.VALUATION_FREQUENCY_UNIT IS NOT NULL
	AND P.VALUATION_FREQUENCY_UNIT <> ' ' 
	AND (
		S.SECURITY_SUB_TYPE_ID NOT IN ('AB100', 'AB103', 'AB106', 'AB107', 'AB108', 'CL001')
		AND S.SECURITY_SUB_TYPE_ID NOT LIKE 'DC%'
	) AND (
		(NEXT_REMARGIN_DATE IS NULL)
		OR (
			NEXT_REMARGIN_DATE IS NOT NULL
			AND trunc(S.NEXT_REMARGIN_DATE) <= trunc(sysdate)
		)
	)
	AND (
		(VALUATED_DATE IS NULL)
		OR (
			VALUATED_DATE IS NOT NULL
			AND trunc(VALUATED_DATE) < trunc(sysdate)
		)
	)  
	AND S.STATUS = 'ACTIVE' FETCH FIRST 200 ROWS ONLY;    
    
    
    
    -- SEE COL ID re CAL 
SELECT CMS_COLLATERAL_ID FROM CMS_VALUATION WHERE valuation_date like '%JAN-23%';

-- void updateValuatedFlagForCollateral(long collateralId)
    UPDATE cms_security SET valuated_date = systimestamp WHERE cms_collateral_id = ?
WHERE S.SECURITY_LOCATION = P.COUNTRY_ISO_CODE
	AND S.SECURITY_SUB_TYPE_ID = P.SECURITY_SUB_TYPE_ID
	AND S.CMS_COLLATERAL_ID = T.REFERENCE_ID
	AND T.TRANSACTION_TYPE = 'COL'
	AND T.STATUS NOT IN ('PENDING_UPDATE', 'PENDING_RETRY')
	AND P.STATUS = 'ACTIVE'  
	AND P.THRESHOLD_PERCENT IS NOT NULL
	AND P.VALUATION_FREQUENCY IS NOT NULL
	AND nvl(P.VALUATION_FREQUENCY, 0) > 0
	AND P.VALUATION_FREQUENCY_UNIT IS NOT NULL
	AND P.VALUATION_FREQUENCY_UNIT <> ' ' 
	AND (
		S.SECURITY_SUB_TYPE_ID NOT IN ('AB100', 'AB103', 'AB106', 'AB107', 'AB108', 'CL001')
		AND S.SECURITY_SUB_TYPE_ID NOT LIKE 'DC%'
	) AND (
		(NEXT_REMARGIN_DATE IS NULL)
		OR (
			NEXT_REMARGIN_DATE IS NOT NULL
			AND trunc(S.NEXT_REMARGIN_DATE) <= trunc(sysdate)
		)
	)
	AND (
		(VALUATED_DATE IS NULL)
		OR (
			VALUATED_DATE IS NOT NULL
			AND trunc(VALUATED_DATE) < trunc(sysdate)
		)
	)  
	AND S.STATUS = 'ACTIVE' FETCH FIRST 200 ROWS ONLY;

    -- SEE COL ID re CAL
    SELECT CMS_COLLATERAL_ID FROM CMS_VALUATION WHERE valuation_date like '%JAN-23%';

-- void updateValuatedFlagForCollateral(long collateralId)
    UPDATE cms_security SET valuated_date = systimestamp WHERE cms_collateral_id = ?

    SELECT CMS_COLLATERAL_ID, valuated_date FROM CMS_SECURITY ORDER BY VALUATED_DATE DESC; -- SIT not OKI