-- ORACLE BULK COLLECT INTO
-- https://blogs.oracle.com/connect/post/bulk-processing-with-bulk-collect-and-forall

CREATE OR REPLACE TYPE NUMBER_ARRAY AS TABLE OF number(19);
/
create or replace PACKAGE HOUSE_KEEP AS
	PROCEDURE process;
	PROCEDURE VALIDATE_INFO;
	PROCEDURE REPLICATE_FAC_RELATED_REC(p_fac_ids IN NUMBER_ARRAY);
	PROCEDURE DELETE_FAC_RELATED_REC(p_fac_ids IN NUMBER_ARRAY);
	PROCEDURE REPLICATE_FAC_RELATED_STG_REC(p_fac_ids IN NUMBER_ARRAY);
	PROCEDURE DELETE_FAC_RELATED_STG_REC(p_fac_ids IN NUMBER_ARRAY);
	PROCEDURE DELETE_FAC_REC(p_fac_ids IN NUMBER_ARRAY);
	--COL
	PROCEDURE REPLICATE_COL_RELATED_REC(p_col_ids IN NUMBER_ARRAY);
	PROCEDURE DELETE_COL_RELATED_REC(p_col_ids IN NUMBER_ARRAY);
	PROCEDURE REPLICATE_COL_RELATED_STG_REC(p_col_ids IN NUMBER_ARRAY);
	PROCEDURE DELETE_COL_RELATED_STG_REC(p_col_ids IN NUMBER_ARRAY);

END HOUSE_KEEP;
/
	create or replace PACKAGE BODY "HOUSE_KEEP" AS

	  PROCEDURE process AS
	  p_fac_ids NUMBER_ARRAY;
	  p_col_ids NUMBER_ARRAY;
	  BEGIN
			
        SELECT CMS_LSP_APPR_LMTS_ID BULK COLLECT INTO p_fac_ids
        FROM sci_lsp_appr_lmts WHERE CMS_LSP_APPR_LMTS_ID IN (20130606000000001,20130619000000025);

		SELECT CMS_COLLATERAL_ID BULK COLLECT INTO p_col_ids
		FROM CMS_SECURITY WHERE CMS_COLLATERAL_ID IN (20130606000000007, 20130606000000009) ;
			
		DBMS_OUTPUT.PUT_LINE ('START process');
		DBMS_OUTPUT.PUT_LINE ('Total facility processing '|| p_fac_ids.count);
		DBMS_OUTPUT.PUT_LINE ('Total facility processing '|| p_col_ids.count);
		
		FOR i IN 1 .. p_fac_ids.count loop
        DBMS_OUTPUT.PUT_LINE ('FACILITY ID: ' || p_fac_ids(i));
        end loop;
		FOR i IN 1 .. p_col_ids.count loop
        DBMS_OUTPUT.PUT_LINE ('FACILITY ID: ' || p_col_ids(i));
        end loop;
		
		VALIDATE_INFO;
		
		REPLICATE_FAC_RELATED_STG_REC(p_fac_ids);
		REPLICATE_FAC_RELATED_REC(p_fac_ids);
--		DELETE_FAC_RELATED_STG_REC(p_fac_ids);
--		DELETE_FAC_RELATED_REC(p_fac_ids);
--		DELETE_FAC_REC(p_fac_ids);

		REPLICATE_TRANSACTION_COL_RELATED_REC(p_col_ids IN NUMBER_ARRAY);
		REPLICATE_COL_RELATED_REC(p_col_ids IN NUMBER_ARRAY);
		REPLICATE_COL_RELATED_STG_REC(p_col_ids IN NUMBER_ARRAY);
		-- DELETE_TRANSACTION_COL_RELATED_REC(p_col_ids IN NUMBER_ARRAY);
		-- DELETE_COL_RELATED_REC(p_col_ids IN NUMBER_ARRAY);
		-- DELETE_COL_RELATED_STG_REC(p_col_ids IN NUMBER_ARRAY);

		
		DBMS_OUTPUT.PUT_LINE ('END process');
	  END process;

	  PROCEDURE VALIDATE_INFO AS
	  BEGIN
	  DBMS_OUTPUT.PUT_LINE ('START VALIDATE_INFO /// TO DO');
	  DBMS_OUTPUT.PUT_LINE ('END VALIDATE_INFO');
	  END VALIDATE_INFO;

	  PROCEDURE REPLICATE_FAC_RELATED_REC(p_fac_ids IN NUMBER_ARRAY) AS
	  BEGIN
		DBMS_OUTPUT.PUT_LINE ('START REPLICATE_FAC_RELATED_REC');
		INSERT INTO HK_SCI_LSP_APPR_LMTS
		SELECT * FROM SCI_LSP_APPR_LMTS
		WHERE LMT_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_FACILITY_MASTER
		SELECT * FROM CMS_FACILITY_MASTER
		WHERE CMS_LSP_APPR_LMTS_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_FAC_RELATIONSHIP
		SELECT * FROM CMS_FAC_RELATIONSHIP
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_FAC_MULTI_TIER_FINANCING
		SELECT * FROM CMS_FAC_MULTI_TIER_FINANCING
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_FAC_PREPAYMENT_LIST
		SELECT * FROM CMS_FAC_PREPAYMENT_LIST
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_FAC_REDUCTION_SCHEDULE
		SELECT * FROM CMS_FAC_REDUCTION_SCHEDULE
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_LSP_APPR_DRAWING_CURR 
		SELECT * FROM CMS_LSP_APPR_DRAWING_CURR 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_FAC_MESSAGE 
		SELECT * FROM CMS_FAC_MESSAGE 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_FAC_INCREMENTAL 
		SELECT * FROM CMS_FAC_INCREMENTAL 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_FAC_REDUCTION_SCHEDULE
		SELECT * FROM CMS_FAC_REDUCTION_SCHEDULE
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_FAC_GENERAL
		SELECT * FROM CMS_FAC_GENERAL
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_FAC_INTEREST 
		SELECT * FROM CMS_FAC_INTEREST 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_FAC_ADDITIONAL 
		SELECT * FROM CMS_FAC_ADDITIONAL 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_FAC_FEE_CHARGE
		SELECT * FROM CMS_FAC_FEE_CHARGE
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_FAC_BNM_CODES 
		SELECT * FROM CMS_FAC_BNM_CODES 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_FAC_ISLAMIC_MASTER
		SELECT * FROM CMS_FAC_ISLAMIC_MASTER
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_FAC_BBA_VARI_PACKAGE
		SELECT * FROM CMS_FAC_BBA_VARI_PACKAGE
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_FAC_RENTAL_RENEWAL
		SELECT * FROM CMS_FAC_RENTAL_RENEWAL
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_FAC_SECURITY_DEPOSIT
		SELECT * FROM CMS_FAC_SECURITY_DEPOSIT
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_FAC_TSPR
		SELECT * FROM CMS_FAC_TSPR
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );
		
		commit;
		DBMS_OUTPUT.PUT_LINE ('END REPLICATE_FAC_RELATED_REC');
	  END REPLICATE_FAC_RELATED_REC;
	  
	  
	  PROCEDURE DELETE_FAC_RELATED_REC(p_fac_ids IN NUMBER_ARRAY) AS
	  BEGIN
		DBMS_OUTPUT.PUT_LINE ('START DELETE_FAC_RELATED_REC');

		DELETE FROM CMS_FACILITY_MASTER
		WHERE CMS_LSP_APPR_LMTS_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_FAC_RELATIONSHIP
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_FAC_MULTI_TIER_FINANCING
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_FAC_PREPAYMENT_LIST
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_FAC_REDUCTION_SCHEDULE
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_LSP_APPR_DRAWING_CURR 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_FAC_MESSAGE 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_FAC_INCREMENTAL 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_FAC_REDUCTION_SCHEDULE
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_FAC_GENERAL
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_FAC_INTEREST 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_FAC_ADDITIONAL 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_FAC_FEE_CHARGE
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_FAC_BNM_CODES 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_FAC_ISLAMIC_MASTER
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_FAC_BBA_VARI_PACKAGE
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_FAC_RENTAL_RENEWAL
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_FAC_SECURITY_DEPOSIT
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_FAC_TSPR
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		commit;
		DBMS_OUTPUT.PUT_LINE ('END DELETE_FAC_RELATED_REC');
	  END DELETE_FAC_RELATED_REC;
	  
	  
	  PROCEDURE REPLICATE_FAC_RELATED_STG_REC(p_fac_ids IN NUMBER_ARRAY) AS
	  BEGIN
		DBMS_OUTPUT.PUT_LINE ('START REPLICATE_FAC_RELATED_STG_REC');
		INSERT INTO HK_CMS_STG_FACILITY_MASTER
		SELECT * FROM CMS_STG_FACILITY_MASTER
		WHERE CMS_LSP_APPR_LMTS_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		
		INSERT INTO HK_CMS_STG_FAC_RELATIONSHIP 
		SELECT * FROM CMS_STG_FAC_RELATIONSHIP 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_STG_FAC_MULTI_TIER_FINANCING 
		SELECT * FROM CMS_STG_FAC_MULTI_TIER_FINANCING 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_STG_FAC_PREPAYMENT_LIST 
		SELECT * FROM CMS_STG_FAC_PREPAYMENT_LIST 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_STG_FAC_REDUCTION_SCHEDULE
		SELECT * FROM CMS_STG_FAC_REDUCTION_SCHEDULE
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_STG_LSP_APPR_DRAWING_CURR 
		SELECT * FROM CMS_STG_LSP_APPR_DRAWING_CURR 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_STG_FAC_MESSAGE 
		SELECT * FROM CMS_STG_FAC_MESSAGE 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_STG_FAC_INCREMENTAL 
		SELECT * FROM CMS_STG_FAC_INCREMENTAL 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_STG_FAC_REDUCTION_SCHEDULE
		SELECT * FROM CMS_STG_FAC_REDUCTION_SCHEDULE
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_STG_FAC_GENERAL 
		SELECT * FROM CMS_STG_FAC_GENERAL 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_STG_FAC_INTEREST 
		SELECT * FROM CMS_STG_FAC_INTEREST 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_STG_FAC_ADDITIONAL 
		SELECT * FROM CMS_STG_FAC_ADDITIONAL 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_STG_FAC_FEE_CHARGE 
		SELECT * FROM CMS_STG_FAC_FEE_CHARGE 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_STG_FAC_BNM_CODES 
		SELECT * FROM CMS_STG_FAC_BNM_CODES 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_STG_FAC_ISLAMIC_MASTER
		SELECT * FROM CMS_STG_FAC_ISLAMIC_MASTER
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_STG_FAC_BBA_VARI_PACKAGE 
		SELECT * FROM CMS_STG_FAC_BBA_VARI_PACKAGE 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_STG_FAC_RENTAL_RENEWAL 
		SELECT * FROM CMS_STG_FAC_RENTAL_RENEWAL 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_STG_FAC_SECURITY_DEPOSIT  
		SELECT * FROM CMS_STG_FAC_SECURITY_DEPOSIT  
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		INSERT INTO HK_CMS_STG_FAC_TSPR
		SELECT * FROM CMS_STG_FAC_TSPR
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );
		
		commit;
		DBMS_OUTPUT.PUT_LINE ('END REPLICATE_FAC_RELATED_STG_REC');
	  END REPLICATE_FAC_RELATED_STG_REC;

	  PROCEDURE DELETE_FAC_RELATED_STG_REC(p_fac_ids IN NUMBER_ARRAY) AS
	  BEGIN
		DBMS_OUTPUT.PUT_LINE ('START DELETE_FAC_RELATED_STG_REC');
		
		DELETE FROM CMS_STG_FACILITY_MASTER 
		WHERE CMS_LSP_APPR_LMTS_ID IN ( SELECT * FROM TABLE(p_fac_ids) );		
		
		DELETE FROM CMS_STG_FAC_RELATIONSHIP 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_STG_FAC_MULTI_TIER_FINANCING 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_STG_FAC_PREPAYMENT_LIST 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_STG_FAC_REDUCTION_SCHEDULE
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_STG_LSP_APPR_DRAWING_CURR 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_STG_FAC_MESSAGE 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_STG_FAC_INCREMENTAL 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_STG_FAC_REDUCTION_SCHEDULE
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_STG_FAC_GENERAL 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_STG_FAC_INTEREST 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_STG_FAC_ADDITIONAL 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_STG_FAC_FEE_CHARGE 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_STG_FAC_BNM_CODES 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_STG_FAC_ISLAMIC_MASTER
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_STG_FAC_BBA_VARI_PACKAGE 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_STG_FAC_RENTAL_RENEWAL 
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_STG_FAC_SECURITY_DEPOSIT  
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		DELETE FROM CMS_STG_FAC_TSPR
		WHERE CMS_FAC_MASTER_ID IN ( SELECT * FROM TABLE(p_fac_ids) );

		commit;
		DBMS_OUTPUT.PUT_LINE ('END DELETE_FAC_RELATED_STG_REC');
	  END DELETE_FAC_RELATED_STG_REC;


	  PROCEDURE DELETE_FAC_REC(p_fac_ids IN NUMBER_ARRAY) AS
	  BEGIN
		DBMS_OUTPUT.PUT_LINE ('START DELETE_FAC_REC');
		DELETE FROM SCI_LSP_APPR_LMTS
		WHERE LMT_ID IN ( SELECT * FROM TABLE(p_fac_ids) );
		
		commit;
		DBMS_OUTPUT.PUT_LINE ('END DELETE_FAC_REC');
	  END DELETE_FAC_REC;

      
	  -- COL and CHECKLIST
	  PROCEDURE REPLICATE_TRANSACTION_COL_RELATED_REC(p_col_ids IN NUMBER_ARRAY) AS
	  BEGIN 
	  	-- CHECKLIST
		INSERT INTO HK_TRANSACTION 
		SELECT * FROM TRANSACTION 
		WHERE TRANSACTION_TYPE = 'CHECKLIST' 
		AND STAGING_REFERENCE_ID IN (
			SELECT CHECKLIST_ID
			FROM STAGE_CHECKLIST
			WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE (p_col_ids))
		) ;

		INSERT INTO HK_TRANS_HISTORY 
		SELECT * FROM TRANS_HISTORY
		WHERE TRANSACTION_ID IN (
			SELECT TRANSACTION_ID FROM TRANSACTION 
			WHERE TRANSACTION_TYPE = 'CHECKLIST' 
			AND STAGING_REFERENCE_ID IN (
				SELECT CHECKLIST_ID
				FROM STAGE_CHECKLIST
				WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE (p_col_ids))
			)
		);

		--CUS DOC
		INSERT INTO HK_TRANSACTION 
		SELECT * FROM TRANSACTION 
		WHERE TRANSACTION_TYPE = 'CUSTODIAN' 
		AND STAGING_REFERENCE_ID IN (
			SELECT CUSTODIAN_DOC_ID
			FROM CMS_STAGE_CUST_DOC
			WHERE CHECKLIST_ID IN (
					SELECT CHECKLIST_ID
					FROM STAGE_CHECKLIST
					WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE (p_col_ids))
			)
		) ;

		INSERT INTO HK_TRANS_HISTORY 
		SELECT * FROM TRANS_HISTORY
		WHERE TRANSACTION_ID IN (
			SELECT TRANSACTION_ID 
			FROM TRANSACTION 
			WHERE TRANSACTION_TYPE = 'CUSTODIAN' 
			AND STAGING_REFERENCE_ID IN (
				SELECT CUSTODIAN_DOC_ID
				FROM CMS_STAGE_CUST_DOC
				WHERE CHECKLIST_ID IN (
					SELECT CHECKLIST_ID
					FROM STAGE_CHECKLIST
					WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE (p_col_ids)
				)
			)
		);
		commit;
		DBMS_OUTPUT.PUT_LINE ('END REPLICATE_TRANSACTION_COL_RELATED_REC');
	  END REPLICATE_TRANSACTION_COL_RELATED_REC;

	PROCEDURE DELETE_TRANSACTION_COL_RELATED_REC(p_col_ids IN NUMBER_ARRAY) AS
	  BEGIN 
		-- CHECKLIST
		DELETE FROM TRANS_HISTORY
		WHERE TRANSACTION_ID IN (
			SELECT TRANSACTION_ID FROM TRANSACTION 
			WHERE TRANSACTION_TYPE = 'CHECKLIST' 
			AND STAGING_REFERENCE_ID IN (
				SELECT CHECKLIST_ID
				FROM STAGE_CHECKLIST
				WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE (p_col_ids))
			)
		);

		DELETE FROM TRANSACTION 
		WHERE TRANSACTION_TYPE = 'CHECKLIST' 
		AND STAGING_REFERENCE_ID IN (
			SELECT CHECKLIST_ID
			FROM STAGE_CHECKLIST
			WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE (p_col_ids))
		) ;

		--CUS DOC
		DELETE FROM TRANS_HISTORY
		WHERE TRANSACTION_ID IN (
			SELECT TRANSACTION_ID 
			FROM TRANSACTION 
			WHERE TRANSACTION_TYPE = 'CUSTODIAN' 
			AND STAGING_REFERENCE_ID IN (
				SELECT CUSTODIAN_DOC_ID
				FROM CMS_STAGE_CUST_DOC
				WHERE CHECKLIST_ID IN (
					SELECT CHECKLIST_ID
					FROM STAGE_CHECKLIST
					WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE (p_col_ids)
				)
			)
		);
		
		DELETE FROM TRANSACTION 
		WHERE TRANSACTION_TYPE = 'CUSTODIAN' 
		AND STAGING_REFERENCE_ID IN (
			SELECT CUSTODIAN_DOC_ID
			FROM CMS_STAGE_CUST_DOC
			WHERE CHECKLIST_ID IN (
					SELECT CHECKLIST_ID
					FROM STAGE_CHECKLIST
					WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE (p_col_ids)
				)
			)
		) ;

		commit;
		DBMS_OUTPUT.PUT_LINE ('END DELETE_TRANSACTION_COL_RELATED_REC');
	  END DELETE_TRANSACTION_COL_RELATED_REC;
	  
	  PROCEDURE REPLICATE_COL_RELATED_REC(p_col_ids IN NUMBER_ARRAY) AS
	  BEGIN 
		INSERT INTO HK_CMS_SECURITY 
		SELECT * FROM CMS_SECURITY 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_cms_cash_deposit  
		SELECT * FROM cms_cash_deposit  
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_sci_sec_pldgr_map 
		SELECT * FROM sci_sec_pldgr_map 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_cms_ca_collateral_map 
		SELECT * FROM cms_ca_collateral_map 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_CHARGE_DETAIL 
		SELECT * FROM CMS_CHARGE_DETAIL 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_LIMIT_CHARGE_MAP  
		SELECT * FROM CMS_LIMIT_CHARGE_MAP  
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_cms_limit_security_map 
		SELECT * FROM cms_limit_security_map 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_ASSET 
		SELECT * FROM CMS_ASSET 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_CASH 
		SELECT * FROM CMS_CASH 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_ASSET_PDC 
		SELECT * FROM CMS_ASSET_PDC 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_VALUATION 
		SELECT * FROM CMS_VALUATION 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_INSURANCE 
		SELECT * FROM CMS_INSURANCE 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_INSURANCE_CDS 
		SELECT * FROM CMS_INSURANCE_CDS 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_MARKETABLE_SEC 
		SELECT * FROM CMS_MARKETABLE_SEC 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_PORTFOLIO_ITEM 
		SELECT * FROM CMS_PORTFOLIO_ITEM 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_DOCUMENT 
		SELECT * FROM CMS_DOCUMENT 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_OTHERS 
		SELECT * FROM CMS_OTHERS 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_GUARANTEE 
		SELECT * FROM CMS_GUARANTEE 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_PROPERTY 
		SELECT * FROM CMS_PROPERTY 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_INSURANCE_POLICY 
		SELECT * FROM CMS_INSURANCE_POLICY 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_ASSET_AIRCRAFT 
		SELECT * FROM CMS_ASSET_AIRCRAFT 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_ASSET_GOLD 
		SELECT * FROM CMS_ASSET_GOLD 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_ASSET_PLANT_EQUIP 
		SELECT * FROM CMS_ASSET_PLANT_EQUIP 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_ASSET_TRADE_IN 
		SELECT * FROM CMS_ASSET_TRADE_IN 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_ASSET_VEHICLE 
		SELECT * FROM CMS_ASSET_VEHICLE 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_ASSET_VESSEL 
		SELECT * FROM CMS_ASSET_VESSEL 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_cms_checklist 
		SELECT * FROM cms_checklist 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_cms_checklist_item 
		SELECT * FROM cms_checklist_item 
		WHERE CHECKLIST_ID IN ( SELECT CHECKLIST_ID FROM CMS_CHECKLIST WHERE CMS_COLLATERAL_ID IN TABLE(p_col_ids)) ;

		INSERT INTO HK_cms_cust_doc 
		SELECT * FROM cms_cust_doc 
		WHERE CHECKLIST_ID IN ( SELECT CHECKLIST_ID FROM CMS_CHECKLIST WHERE CMS_COLLATERAL_ID IN TABLE(p_col_ids)) ;

		INSERT INTO HK_cms_cust_doc_item 
		SELECT * FROM cms_cust_doc_item 
		WHERE CUSTODIAN_DOC_ID IN (
			SELECT CUSTODIAN_DOC_ID FROM cms_cust_doc 
			WHERE CHECKLIST_ID IN ( SELECT CHECKLIST_ID FROM CMS_CHECKLIST WHERE CMS_COLLATERAL_ID IN TABLE(p_col_ids)) ;
		) ;

		INSERT INTO HK_sci_lsp_appr_lmts		 
		SELECT * FROM sci_lsp_appr_lmts 
		WHERE CMS_LSP_APPR_LMTS_ID IN ( 
			SELECT CMS_LSP_APPR_LMTS_ID 
			FROM CMS_LIMIT_CHARGE_MAP
			WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids))
		) ;

		commit;
		DBMS_OUTPUT.PUT_LINE ('END REPLICATE_COL_RELATED_REC');
	  END REPLICATE_COL_RELATED_REC;

	  PROCEDURE REPLICATE_COL_RELATED_STG_REC(p_col_ids IN NUMBER_ARRAY);
	  BEGIN 
		INSERT INTO HK_CMS_STAGE_SECURITY 
		SELECT * FROM CMS_STAGE_SECURITY 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_STAGE_cash_deposit  
		SELECT * FROM CMS_STAGE_cash_deposit  
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_STAGE_CHARGE_DETAIL 
		SELECT * FROM CMS_STAGE_CHARGE_DETAIL 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_STAGE_LIMIT_CHARGE_MAP  
		SELECT * FROM CMS_STAGE_LIMIT_CHARGE_MAP  
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_STAGE_limit_security_map 
		SELECT * FROM CMS_STAGE_limit_security_map 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_STAGE_ASSET 
		SELECT * FROM CMS_STAGE_ASSET 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_STAGE_CASH 
		SELECT * FROM CMS_STAGE_CASH 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_STAGE_ASSET_PDC 
		SELECT * FROM CMS_STAGE_ASSET_PDC 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_STAGE_VALUATION 
		SELECT * FROM CMS_STAGE_VALUATION 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_STAGE_INSURANCE 
		SELECT * FROM CMS_STAGE_INSURANCE 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_STAGE_INSURANCE_CDS 
		SELECT * FROM CMS_STAGE_INSURANCE_CDS 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_STAGE_MARKETABLE_SEC 
		SELECT * FROM CMS_STAGE_MARKETABLE_SEC 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_STAGE_PORTFOLIO_ITEM 
		SELECT * FROM CMS_STAGE_PORTFOLIO_ITEM 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_STAGE_DOCUMENT 
		SELECT * FROM CMS_STAGE_DOCUMENT 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_STAGE_OTHERS 
		SELECT * FROM CMS_STAGE_OTHERS 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_STAGE_GUARANTEE 
		SELECT * FROM CMS_STAGE_GUARANTEE 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_STAGE_PROPERTY 
		SELECT * FROM CMS_STAGE_PROPERTY 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_STAGE_INSURANCE_POLICY 
		SELECT * FROM CMS_STAGE_INSURANCE_POLICY 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_STAGE_ASSET_AIRCRAFT 
		SELECT * FROM CMS_STAGE_ASSET_AIRCRAFT 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_STAGE_ASSET_GOLD 
		SELECT * FROM CMS_STAGE_ASSET_GOLD 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;


		INSERT INTO HK_CMS_STAGE_ASSET_PLANT_EQUIP 
		SELECT * FROM CMS_STAGE_ASSET_PLANT_EQUIP 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_STAGE_ASSET_TRADE_IN 
		SELECT * FROM STAGE_ASSET_TRADE_IN 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_STAGE_ASSET_VEHICLE 
		SELECT * FROM CMS_STAGE_ASSET_VEHICLE 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_CMS_STAGE_ASSET_VESSEL 
		SELECT * FROM CMS_STAGE_ASSET_VESSEL 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

		INSERT INTO HK_STAGE_CHECKLIST 
		SELECT * FROM STAGE_CHECKLIST 
		WHERE CMS_COLLATERAL_ID IN ( SELECT * FROM TABLE(p_col_ids)) ;

	    INSERT INTO HK_STAGE_CHECKLIST_ITEM 
		SELECT * FROM STAGE_CHECKLIST_ITEM 
		WHERE CHECKLIST_ID IN ( SELECT CHECKLIST_ID FROM STAGE_CHECKLIST WHERE CMS_COLLATERAL_ID IN TABLE(p_col_ids)) ;

		INSERT INTO HK_cms_stage_cust_doc 
		SELECT * FROM cms_stage_cust_doc 
		WHERE CHECKLIST_ID IN ( SELECT CHECKLIST_ID FROM STAGE_CHECKLIST WHERE CMS_COLLATERAL_ID IN TABLE(p_col_ids)) ;

		INSERT INTO HK_cms_stage_cust_doc_item 
		SELECT * FROM cms_stage_cust_doc_item 
		WHERE CUSTODIAN_DOC_ID IN (
			SELECT CUSTODIAN_DOC_ID FROM cms_stage_cust_doc 
			WHERE CHECKLIST_ID IN ( SELECT CHECKLIST_ID FROM STAGE_CHECKLIST WHERE CMS_COLLATERAL_ID IN TABLE(p_col_ids)) ;
		) ;

	  	commit;
		DBMS_OUTPUT.PUT_LINE ('END REPLICATE_COL_RELATED_STG_REC');
	  END REPLICATE_COL_RELATED_STG_REC;

	  PROCEDURE DELETE_COL_RELATED_REC(p_col_ids IN NUMBER_ARRAY);
	  BEGIN 
		DELETE FROM CMS_SECURITY WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM cms_cash_deposit  WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM sci_sec_pldgr_map WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM cms_ca_collateral_map WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_CHARGE_DETAIL WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_LIMIT_CHARGE_MAP  WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM cms_limit_security_map WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_ASSET WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_CASH WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_ASSET_PDC WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_VALUATION WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_INSURANCE WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_INSURANCE_CDS WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_MARKETABLE_SEC WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_PORTFOLIO_ITEM WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_DOCUMENT WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_OTHERS WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_GUARANTEE WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_PROPERTY WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_INSURANCE_POLICY WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_ASSET_AIRCRAFT WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_ASSET_GOLD WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_ASSET_PLANT_EQUIP WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_ASSET_TRADE_IN WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_ASSET_VEHICLE WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_ASSET_VESSEL WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM cms_checklist WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM cms_checklist_item WHERE CHECKLIST_ID IN ( SELECT CHECKLIST_ID FROM CMS_CHECKLIST WHERE CMS_COLLATERAL_ID IN TABLE(p_col_ids)) ;
		DELETE FROM cms_cust_doc WHERE CHECKLIST_ID IN ( SELECT CHECKLIST_ID FROM CMS_CHECKLIST WHERE CMS_COLLATERAL_ID IN TABLE(p_col_ids)) ;
		DELETE FROM cms_cust_doc_item WHERE CUSTODIAN_DOC_ID IN (
			SELECT CUSTODIAN_DOC_ID FROM cms_cust_doc 
			WHERE CHECKLIST_ID IN ( SELECT CHECKLIST_ID FROM CMS_CHECKLIST WHERE CMS_COLLATERAL_ID IN TABLE(p_col_ids)) ;
		) ;

		DELETE FROM sci_lsp_appr_lmts WHERE CMS_LSP_APPR_LMTS_ID IN ( 
			SELECT CMS_LSP_APPR_LMTS_ID 
			FROM CMS_LIMIT_CHARGE_MAP
			WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids))
		) ;
	  	commit;
		DBMS_OUTPUT.PUT_LINE ('END DELETE_COL_RELATED_REC');
	  END DELETE_COL_RELATED_REC;

	  PROCEDURE DELETE_COL_RELATED_STG_REC(p_col_ids IN NUMBER_ARRAY);
	  BEGIN 
		DELETE FROM CMS_STAGE_SECURITY WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_STAGE_cash_deposit  WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_STAGE_CHARGE_DETAIL WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_STAGE_LIMIT_CHARGE_MAP  WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_STAGE_limit_security_map WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_STAGE_ASSET WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_STAGE_CASH WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_STAGE_ASSET_PDC WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_STAGE_VALUATION WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_STAGE_INSURANCE WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_STAGE_INSURANCE_CDS WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_STAGE_MARKETABLE_SEC WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_STAGE_PORTFOLIO_ITEM WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_STAGE_DOCUMENT WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_STAGE_OTHERS WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_STAGE_GUARANTEE WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_STAGE_PROPERTY WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_STAGE_INSURANCE_POLICY WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_STAGE_ASSET_AIRCRAFT WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_STAGE_ASSET_GOLD WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_STAGE_ASSET_PLANT_EQUIP WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM STAGE_ASSET_TRADE_IN WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_STAGE_ASSET_VEHICLE WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM CMS_STAGE_ASSET_VESSEL WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM STAGE_CHECKLIST WHERE CMS_COLLATERAL_ID IN (SELECT * FROM TABLE(p_col_ids));
		DELETE FROM STAGE_CHECKLIST_ITEM 
		WHERE CHECKLIST_ID IN ( SELECT CHECKLIST_ID FROM STAGE_CHECKLIST WHERE CMS_COLLATERAL_ID IN TABLE(p_col_ids)) ;

		DELETE FROM cms_stage_cust_doc 
		WHERE CHECKLIST_ID IN ( SELECT CHECKLIST_ID FROM STAGE_CHECKLIST WHERE CMS_COLLATERAL_ID IN TABLE(p_col_ids)) ;

		DELETE FROM cms_stage_cust_doc_item 
		WHERE CUSTODIAN_DOC_ID IN (
			SELECT CUSTODIAN_DOC_ID FROM cms_stage_cust_doc 
			WHERE CHECKLIST_ID IN ( SELECT CHECKLIST_ID FROM STAGE_CHECKLIST WHERE CMS_COLLATERAL_ID IN TABLE(p_col_ids)) ;
		) ;

	  	commit;
		DBMS_OUTPUT.PUT_LINE ('END DELETE_COL_RELATED_STG_REC');
	  END DELETE_COL_RELATED_STG_REC;

	END HOUSE_KEEP;
	/
    
call HOUSE_KEEP.process();    
