SELECT CMS_COLLATERAL_ID
FROM CMS_VALUATION
WHERE valuation_date LIKE '%JAN-23%';
SELECT *
FROM cms_valuation
WHERE VALUATION_DATE IS NOT NULL
ORDER BY valuation_date DESC;
--20-OCT-22
SELECT CMS_COLLATERAL_ID
FROM CMS_VALUATION
WHERE valuation_date LIKE '%OCT-22%';
--count COLL
SELECT COUNT(1)
FROM CMS_SECURITY S,
	CMS_SECURITY_PARAMETER P,
	TRANSACTION T
WHERE S.SECURITY_LOCATION = P.COUNTRY_ISO_CODE
	AND S.SECURITY_SUB_TYPE_ID = P.SECURITY_SUB_TYPE_ID
	AND S.CMS_COLLATERAL_ID = T.REFERENCE_ID
	AND T.TRANSACTION_TYPE = 'COL'
	AND T.STATUS NOT IN ('PENDING_UPDATE', 'PENDING_RETRY')
	AND P.STATUS = 'ACTIVE'
	AND P.THRESHOLD_PERCENT IS NOT NULL
	AND P.VALUATION_FREQUENCY IS NOT NULL
	AND nvl(P.VALUATION_FREQUENCY, 0) > 0
	AND P.VALUATION_FREQUENCY_UNIT IS NOT NULL
	AND P.VALUATION_FREQUENCY_UNIT <> ' '
	AND (
		S.SECURITY_SUB_TYPE_ID NOT IN (
			'AB100',
			'AB103',
			'AB106',
			'AB107',
			'AB108',
			'CL001'
		)
		AND S.SECURITY_SUB_TYPE_ID NOT LIKE 'DC%'
	)
	AND (
		(NEXT_REMARGIN_DATE IS NULL)
		OR (
			NEXT_REMARGIN_DATE IS NOT NULL
			AND trunc(S.NEXT_REMARGIN_DATE) <= trunc(sysdate)
		)
	)
	AND (
		(VALUATED_DATE IS NULL)
		OR (
			VALUATED_DATE IS NOT NULL
			AND trunc(VALUATED_DATE) < trunc(sysdate)
		)
	)
	AND S.STATUS = 'ACTIVE';
-- PICK COL
SELECT S.CMS_COLLATERAL_ID,
	VALUATED_DATE,
	S.SCI_SECURITY_DTL_ID,
	S.SCI_SECURITY_TYPE_VALUE,
	S.SCI_SECURITY_SUBTYPE_VALUE,
	S.SECURITY_LOCATION,
	S.SCI_SECURITY_TYPE_VALUE
FROM CMS_SECURITY S,
	CMS_SECURITY_PARAMETER P,
	TRANSACTION T
WHERE S.SECURITY_LOCATION = P.COUNTRY_ISO_CODE
	AND S.SECURITY_SUB_TYPE_ID = P.SECURITY_SUB_TYPE_ID
	AND S.CMS_COLLATERAL_ID = T.REFERENCE_ID
	AND T.TRANSACTION_TYPE = 'COL'
	AND T.STATUS NOT IN ('PENDING_UPDATE', 'PENDING_RETRY')
	AND P.STATUS = 'ACTIVE'
	AND P.THRESHOLD_PERCENT IS NOT NULL
	AND P.VALUATION_FREQUENCY IS NOT NULL
	AND nvl(P.VALUATION_FREQUENCY, 0) > 0
	AND P.VALUATION_FREQUENCY_UNIT IS NOT NULL
	AND P.VALUATION_FREQUENCY_UNIT <> ' '
	AND (
		S.SECURITY_SUB_TYPE_ID NOT IN (
			'AB100',
			'AB103',
			'AB106',
			'AB107',
			'AB108',
			'CL001'
		)
		AND S.SECURITY_SUB_TYPE_ID NOT LIKE 'DC%'
	)
	AND (
		(NEXT_REMARGIN_DATE IS NULL)
		OR (
			NEXT_REMARGIN_DATE IS NOT NULL
			AND trunc(S.NEXT_REMARGIN_DATE) <= trunc(sysdate)
		)
	)
	AND (
		(VALUATED_DATE IS NULL)
		OR (
			VALUATED_DATE IS NOT NULL
			AND trunc(VALUATED_DATE) < trunc(sysdate)
		)
	)
	AND S.STATUS = 'ACTIVE'
FETCH FIRST 200 ROWS ONLY;
-- SEE COL ID re CAL 
SELECT CMS_COLLATERAL_ID
FROM CMS_VALUATION
WHERE valuation_date like '%JAN-23%';
-- void updateValuatedFlagForCollateral(long collateralId)
UPDATE cms_security
SET valuated_date = systimestamp
WHERE cms_collateral_id = ?
WHERE S.SECURITY_LOCATION = P.COUNTRY_ISO_CODE
	AND S.SECURITY_SUB_TYPE_ID = P.SECURITY_SUB_TYPE_ID
	AND S.CMS_COLLATERAL_ID = T.REFERENCE_ID
	AND T.TRANSACTION_TYPE = 'COL'
	AND T.STATUS NOT IN ('PENDING_UPDATE', 'PENDING_RETRY')
	AND P.STATUS = 'ACTIVE'
	AND P.THRESHOLD_PERCENT IS NOT NULL
	AND P.VALUATION_FREQUENCY IS NOT NULL
	AND nvl(P.VALUATION_FREQUENCY, 0) > 0
	AND P.VALUATION_FREQUENCY_UNIT IS NOT NULL
	AND P.VALUATION_FREQUENCY_UNIT <> ' '
	AND (
		S.SECURITY_SUB_TYPE_ID NOT IN (
			'AB100',
			'AB103',
			'AB106',
			'AB107',
			'AB108',
			'CL001'
		)
		AND S.SECURITY_SUB_TYPE_ID NOT LIKE 'DC%'
	)
	AND (
		(NEXT_REMARGIN_DATE IS NULL)
		OR (
			NEXT_REMARGIN_DATE IS NOT NULL
			AND trunc(S.NEXT_REMARGIN_DATE) <= trunc(sysdate)
		)
	)
	AND (
		(VALUATED_DATE IS NULL)
		OR (
			VALUATED_DATE IS NOT NULL
			AND trunc(VALUATED_DATE) < trunc(sysdate)
		)
	)
	AND S.STATUS = 'ACTIVE'
FETCH FIRST 200 ROWS ONLY;
-- SEE COL ID re CAL
SELECT CMS_COLLATERAL_ID
FROM CMS_VALUATION
WHERE valuation_date like '%JAN-23%';
-- void updateValuatedFlagForCollateral(long collateralId)
UPDATE cms_security
SET valuated_date = systimestamp
WHERE cms_collateral_id = ?
SELECT CMS_COLLATERAL_ID,
	valuated_date
FROM CMS_SECURITY
ORDER BY VALUATED_DATE DESC;
-- SIT not OKI
SELECT CMS_COLLATERAL_ID,
	valuated_date
FROM CMS_SECURITY
WHERE valuated_date IS NOT NULL
ORDER BY VALUATED_DATE DESC;
select *
from CMS_BATCH_JOB
where class_name like '%ValuationMain%'
order by start_date desc;
SELECT *
FROM cms_valuation
WHERE VALUATION_DATE IS NOT NULL
ORDER BY valuation_date DESC;
-- 2/6/ RUN TIME : NULL POINTER EXP ROLLBACK:
SELECT sec.cms_collateral_id,
	SEC.CMV_CURRENCY,
	SEC.CMV,
	SEC.SCI_SECURITY_CURRENCY,
	PR.POSTCODE,
	PR.STATE,
	PR.DISTRICT,
	PR.MUKIM,
	PR.LAND_AREA,
	PR.LAND_AREA_UOM,
	PR.BUILTUP_AREA,
	PR.BUILTUP_AREA_UOM,
	PR.SALE_PURCHASE_VALUE,
	PR.SALE_PURCHASE_DATE,
	PR.PROPERTY_TYPE,
	PR.PROPERTY_COMPLETION_STATUS,
	PR.CATEGORY_OF_LAND_USE
FROM CMS_SECURITY SEC,
	CMS_PROPERTY PR
WHERE SEC.CMS_COLLATERAL_ID IN (20200614000030066, 20200615000030068)
	AND SEC.CMS_COLLATERAL_ID = PR.CMS_COLLATERAL_ID;

--  06 Feb 2023 10:58:44,555:com.integrosys.cms.app.collateral.bus.valuation.dao.PropertyValuationOracleDAO -  MQ SQL REVALUATION : SELECT SOURCE_TYPE, VALUATION_DATE, VALUATION_CURRENCY, CMV, FSV, VALUER, HAIRCUT, REVAL_FREQ, REVAL_FREQ_UNIT  FROM ( SELECT SOURCE_TYPE, VALUATION_DATE, VALUATION_CURRENCY, CMV, FSV, VALUER, HAIRCUT, REVAL_FREQ, REVAL_FREQ_UNIT , row_number() over(ORDER BY VALUATION_DATE DESC, VALUATION_ID DESC) ROWNUM1  FROM CMS_VALUATION WHERE SOURCE_TYPE = ? AND CMS_COLLATERAL_ID = ?  UNION ALL SELECT SOURCE_TYPE, VALUATION_DATE, VALUATION_CURRENCY, CMV, FSV, VALUER, HAIRCUT, REVAL_FREQ, REVAL_FREQ_UNIT , row_number() over(ORDER BY VALUATION_DATE DESC, LOS_VALUATION_ID DESC, VALUATION_ID DESC) ROWNUM1  FROM CMS_VALUATION WHERE SOURCE_TYPE = ? AND CMS_COLLATERAL_ID = ?  UNION ALL SELECT SOURCE_TYPE, VALUATION_DATE, VALUATION_CURRENCY, CMV, FSV, VALUER, HAIRCUT, REVAL_FREQ, REVAL_FREQ_UNIT , row_number() over(ORDER BY VALUATION_DATE DESC, VALUATION_ID DESC) ROWNUM1  FROM CMS_VALUATION WHERE SOURCE_TYPE = ? AND CMS_COLLATERAL_ID = ?  ) WHERE ROWNUM1 = 1
-- 218813 [[ACTIVE] ExecuteThread: '6' for queue: 'weblogic.kernel.Default (self-tuning)'] WARN com.integrosys.cms.batch.valuation.ValuationMain - [UnknownError]   Security SubType [PT704]        Collateral ID [20200615000030068]       Security ID [null]      [Unexpected Error!! Please Trace!!]     [error encountered includes: Runtime Exception Encountered!; nested exception is java.lang.NullPointerException]
SELECT SOURCE_TYPE,
	VALUATION_DATE,
	VALUATION_CURRENCY,
	CMV,
	FSV,
	VALUER,
	HAIRCUT,
	REVAL_FREQ,
	REVAL_FREQ_UNIT
FROM (
		SELECT SOURCE_TYPE,
			VALUATION_DATE,
			VALUATION_CURRENCY,
			CMV,
			FSV,
			VALUER,
			HAIRCUT,
			REVAL_FREQ,
			REVAL_FREQ_UNIT,
			row_number() over(
				ORDER BY VALUATION_DATE DESC,
					VALUATION_ID DESC
			) ROWNUM1
		FROM CMS_VALUATION
		WHERE 
			-- SOURCE_TYPE = ? AND 
			CMS_COLLATERAL_ID = 20200615000030068
		UNION ALL
		SELECT SOURCE_TYPE,
			VALUATION_DATE,
			VALUATION_CURRENCY,
			CMV,
			FSV,
			VALUER,
			HAIRCUT,
			REVAL_FREQ,
			REVAL_FREQ_UNIT,
			row_number() over(
				ORDER BY VALUATION_DATE DESC,
					LOS_VALUATION_ID DESC,
					VALUATION_ID DESC
			) ROWNUM1
		FROM CMS_VALUATION
		WHERE 
			-- SOURCE_TYPE = ? AND 
			CMS_COLLATERAL_ID = 20200615000030068
		UNION ALL
		SELECT SOURCE_TYPE,
			VALUATION_DATE,
			VALUATION_CURRENCY,
			CMV,
			FSV,
			VALUER,
			HAIRCUT,
			REVAL_FREQ,
			REVAL_FREQ_UNIT,
			row_number() over(
				ORDER BY VALUATION_DATE DESC,
					VALUATION_ID DESC
			) ROWNUM1
		FROM CMS_VALUATION
		WHERE 
			-- SOURCE_TYPE = ? AND 
			CMS_COLLATERAL_ID = 20200615000030068
	)
WHERE ROWNUM1 = 1;

-- S	15-JUN-20	VND	111111		aa	33	2	3
-- S	15-JUN-20	VND	111111		aa	33	2	3
-- S	15-JUN-20	VND	111111		aa	33	2	3


-- XÁC ĐỊNH NGUYÊN NHÂN DO TRƯỜNG FSV BỊ NULL KHI XỬ LÝ TRONG CLASS: D:\VTBCLIMS\src\com\integrosys\cms\app\collateral\bus\valuation\dao\GenericValuationOracleDAO.java

SELECT * FROM CMS_VALUATION WHERE FSV IS NULL ; 
SELECT COUNT(*) FROM cms_valuation ;

--FSV NULL 
-- 20200614001442746	VND	02-JUN-20	Quoc Toan	111111	
-- 20200615001442752	VND	15-JUN-20	aa	111111	
-- 20200614001442748	VND	29-MAY-20	Quoc Toan Quoc Toan Quoc Toan Quoc Toan	111111	
-- 20200614001442750	VND	01-MAY-20	aa22	100000000	
-- 20200612001442744	VND	12-JUN-20	Quoc Toan	111111	
-- 20210819001442758	VND	19-AUG-21	ThangPC	1500000000	
-- 20210820001442760	VND	06-AUG-21	ThangPC	1500000000	

UPDATE CMS_VALUATION SET FSV = 1750000000 WHERE VALUATION_ID IN (20200614001442746,20200615001442752,20200614001442748,20200614001442750,20200612001442744,20210819001442758,20210820001442760);
COMMIT ;

SELECT * FROM CMS_VALUATION WHERE VALUATION_ID IN (20200614001442746,20200615001442752,20200614001442748,20200614001442750,20200612001442744,20210819001442758,20210820001442760);