sqlplus rlosvietin/rlosvietin@(description=(address=(protocol=tcp)(host=localhost)(port=1521))(connect_data=(sid=orcl)))

UPDATE LOS_USER SET ENABLE_IND ='Y' ;

SELECT * FROM   LOS_CA ORDER BY ID OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY;

SELECT ID FROM   LOS_CA ORDER BY ID DESC OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY;

SQL> column id format 99999999999999999.99 ;
SQL> SELECT ID FROM   LOS_CA ORDER BY ID DESC OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY;

--FORMAAT
set lines 300;
set trimout on;
set pagesize 10000;
set tab off;
set wrap on;

SELECT ID, APP_REF_NO, ELIGIBILITY_SCORE_TIMES FROM LOS_CA WHERE APP_REF_NO = '12498MO23000009' ORDER BY ID OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY;


<sql-query name="system.sysvalue.maker.list" resultset-ref="sysvalue.staging.list">
 	<![CDATA[
 	 	SELECT DISTINCT
        SA.ID AS ID,
        SA.CODE AS CODE,
        SA.VALUE AS VALUE,
        SA.DESCRIPTION AS DESCRIPTION,
        SA.REMARKS AS REMARKS,
	SA.SYS_FLAG AS SYS_FLAG,
	SA.OTHER_FLAG AS OTHER_FLAG,
        TRX.STATUS AS STATUS,
        TRX.USER_STATUS AS USER_STATUS,
        TRX.LAST_UPDATE AS LAST_UPDATE,
        TRX.CREATED_BY AS CREATED_BY_ID,
		(SELECT USR.SURNAME||' '||USR.FIRST_NAME
	         FROM LOS_USER USR
	         WHERE USR.ID = TRX.CREATED_BY AND USR.STATUS='ACTIVE') AS CREATED_BY,
        (SELECT USR.SURNAME||' '||USR.FIRST_NAME
	         FROM LOS_USER USR
	         WHERE USR.ID = TRX.APPROVED_BY AND USR.STATUS='ACTIVE') AS APPROVED_BY,
        TRX.ID AS TRX_ID,
        TRX.VERSION_TIME AS VERSIONTIME
    FROM
        LOS_SA_VALUE SA,
        LOS_TRX_ADMIN TRX
    WHERE
        TRX.REFERENCE_ID = SA.ID        
        AND (TRX.STATUS = 'ACTIVE' OR TRX.STATUS='EXPIRED')
        AND TRX.TRANSACTION_TYPE = 'SYSVALUE'        
        AND SA.ID NOT IN(
            SELECT DISTINCT SA_STAGING.REFERENCE_ID
            FROM LOS_SA_VALUE_STAGING SA_STAGING,
                 LOS_TRX_ADMIN TRX
            WHERE TRX.STAGING_REF_ID = SA_STAGING.ID
                AND TRX.TRANSACTION_TYPE = 'SYSVALUE'
                AND (TRX.STATUS LIKE 'PENDING%' OR TRX.STATUS LIKE 'REJECTED%' OR TRX.STATUS LIKE 'DRAFT%')
            )
	UNION

	SELECT  DISTINCT
        SA_STAGING.ID AS ID,
        SA_STAGING.CODE AS CODE,
        SA_STAGING.VALUE AS VALUE,
        SA_STAGING.DESCRIPTION AS DESCRIPTION,
        SA_STAGING.REMARKS AS REMARKS,
	SA_STAGING.SYS_FLAG AS SYS_FLAG,
	SA_STAGING.OTHER_FLAG AS OTHER_FLAG, 
        TRX.STATUS AS STATUS,
        TRX.USER_STATUS AS USER_STATUS,
        TRX.LAST_UPDATE AS LAST_UPDATE,
        TRX.CREATED_BY AS CREATED_BY_ID,
		(SELECT USR.SURNAME||' '||USR.FIRST_NAME
	         FROM LOS_USER USR
	         WHERE USR.ID = TRX.CREATED_BY AND USR.STATUS='ACTIVE') AS CREATED_BY,
        (SELECT USR.SURNAME||' '||USR.FIRST_NAME
	         FROM LOS_USER USR
	         WHERE USR.ID = TRX.APPROVED_BY AND USR.STATUS='ACTIVE') AS APPROVED_BY,
        TRX.ID AS TRX_ID,
        TRX.VERSION_TIME AS VERSIONTIME
    FROM
        LOS_SA_VALUE_STAGING SA_STAGING,
        LOS_TRX_ADMIN TRX
    WHERE
        TRX.STAGING_REF_ID = SA_STAGING.ID
        AND TRX.TRANSACTION_TYPE = 'SYSVALUE'
        AND (TRX.STATUS LIKE 'PENDING%' OR TRX.STATUS LIKE 'REJECTED%' OR TRX.STATUS LIKE 'DRAFT%')
       ]]>
    </sql-query>