-- GET ALL ORDER UPDATED BY PREVIOUS DATE:
SELECT
    o.* 
FROM 
    ORDER o
WHERE o.SHOP_ID = ? AND o.LAST_UPDATE_DATE = ?;

-- GET TOTAL NUMBER OF ORDER UPDATED
SELECT
    COUNT(*) AS numberOfOrders, 
    o.* 
FROM 
    ORDER o
WHERE o.SHOP_ID = ? AND o.LAST_UPDATE_DATE = ?;

--TOTAL OF NEW ORDER
SELECT
    COUNT(*) AS numberOfNewOrders, 
    o.* 
FROM 
    ORDER o
WHERE o.SHOP_ID = ? AND o.LAST_UPDATE_DATE = ?
    AND o.STATUS_CODE = ? ;

-- GET TOTAL VALUE OF ORDER UPDATED
-- INCREASE  : PHASE 1  :NEW ORDER CREATED - > ESTIMATE REVENUE
SELECT SUM()
    FROM ORDER o
WHERE o.SHOP_ID = ? AND o.LAST_UPDATE_DATE = ?
    AND o.STATUS_CODE = ? ; 


-- MONEY SHIP TAKE : PHASE 2

-- MONEY DECREASE : CANCEL of < ESTIMATED

